/**
 * Data for the dedicated `npm run seed:destinations` command.
 *
 * Everything here is original placeholder content — no copied descriptions,
 * pricing or branding from any reference site. Images are royalty-free
 * Unsplash URLs, in the same `images.unsplash.com/{photo-id}` form already
 * used across `seed-data.ts`; a broken/rotated id degrades gracefully to the
 * app's branded placeholder (see `SmartImage`) rather than a broken image.
 *
 * NEW_DESTINATIONS: full records for places that don't exist yet anywhere in
 * the seed data (cross-checked against `seed-data.ts` and
 * `seed-demo-packages.ts` by slug).
 *
 * EXISTING_DESTINATION_BACKFILL: safe-field-only updates for destinations
 * that already exist — adds the newer taxonomy fields (type, hotelFeatured,
 * packageFeatured, displayOrder, aliases, parentDestination, isDemoData)
 * without touching any content field an admin may have since edited. The
 * seed script only ever backfills a field that is currently unset.
 */

const img = (id: string, alt: string) => {
  if (/^https?:\/\//i.test(id)) return { url: id, alt };
  const cleanId = id.replace(/\?.*$/, "");
  return { url: `https://images.unsplash.com/${cleanId}?w=1600&q=80&fm=webp`, alt };
};

export type DestinationTypeSeed = "country" | "city" | "region" | "emirate";

export interface NewDestinationSeed {
  name: string;
  slug: string;
  aliases: string[];
  country: string;
  countryCode: string;
  region: string;
  type: DestinationTypeSeed;
  /** Slug of another entry in this file (or an existing destination) — resolved to an ObjectId by the seed script. */
  parentSlug?: string;
  scope: "domestic" | "international";
  themes: string[];
  summary: string;
  description: string;
  heroImage: { url: string; alt: string };
  gallery: { url: string; alt: string }[];
  startingPriceINR: number;
  recommendedDurationDays: number;
  bestMonths: string[];
  currencyUsed: string;
  languages: string[];
  timezone: string;
  visaNote: string;
  coordinates: { lat: number; lng: number };
  highlights: string[];
  faqs: { question: string; answer: string }[];
  isFeatured: boolean;
  isTrending: boolean;
  hotelFeatured: boolean;
  packageFeatured: boolean;
  displayOrder: number;
  status: "draft" | "scheduled" | "published" | "archived";
}

/* -------------------------------------------------------------------------- */
/*                     New — curated for the homepage rail                    */
/* -------------------------------------------------------------------------- */

export const NEW_DESTINATIONS: NewDestinationSeed[] = [
  {
    name: "Japan",
    slug: "japan",
    aliases: [],
    country: "Japan",
    countryCode: "JP",
    region: "East Asia",
    type: "country",
    scope: "international",
    themes: ["luxury", "solo", "family"],
    summary: "Tokyo's pace, Osaka's food, and a rail network that makes all of it easy to string together.",
    description:
      "Beyond Kyoto's temples, Japan is Tokyo's neighbourhoods each feeling like a different city, Osaka's street food culture, and a Shinkansen network precise enough to plan a whole trip around. We build most first-time itineraries across two or three cities rather than one, since the trains make that genuinely easy.",
    heroImage: img("photo-1540959733332-eab4deabeeaf", "Mount Fuji seen beyond a torii gate"),
    gallery: [img("photo-1524413840807-0c3cb6fa808d", "A busy Tokyo crossing at night")],
    startingPriceINR: 130000,
    recommendedDurationDays: 7,
    bestMonths: ["Mar", "Apr", "Oct", "Nov"],
    currencyUsed: "Japanese Yen (JPY)",
    languages: ["Japanese"],
    timezone: "GMT+9",
    visaNote: "Indian passport holders need a visa in advance; typical processing is 5-7 working days.",
    coordinates: { lat: 35.6762, lng: 139.6503 },
    highlights: [
      "Tokyo neighbourhoods that each feel like a different city",
      "Osaka's street food, block by block",
      "A Shinkansen network that makes multi-city trips genuinely easy",
      "Mount Fuji viewpoints without a group tour bus",
    ],
    faqs: [
      {
        question: "Should we do Tokyo and Kyoto, or just one city?",
        answer:
          "For a first trip of a week or more, both — the bullet train between them is under three hours and it's honestly one of the best parts of the trip.",
      },
    ],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 7,
    status: "published",
  },
  {
    name: "Mauritius",
    slug: "mauritius",
    aliases: [],
    country: "Mauritius",
    countryCode: "MU",
    region: "Indian Ocean",
    type: "country",
    scope: "international",
    themes: ["honeymoon", "luxury", "beach"],
    summary: "Lagoon-calm beaches on the west coast, and a lot more going on inland than the resort brochures show.",
    description:
      "Mauritius resorts sell the lagoon, and it's genuinely that calm. What's worth adding is a day inland — Chamarel's coloured earth, a rum distillery tour, or the Black River Gorges — so the trip isn't spent entirely poolside, however good that pool is.",
    heroImage: img("photo-1544644181-1484b3fdfc62", "A turquoise lagoon beach in Mauritius"),
    gallery: [img("photo-1573843981267-be1999ff37cd", "Palm trees over a calm lagoon")],
    startingPriceINR: 110000,
    recommendedDurationDays: 6,
    bestMonths: ["May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov"],
    currencyUsed: "Mauritian Rupee (MUR)",
    languages: ["English", "French", "Mauritian Creole"],
    timezone: "GMT+4",
    visaNote: "Visa-free entry for Indian passport holders for stays up to 90 days.",
    coordinates: { lat: -20.3484, lng: 57.5522 },
    highlights: [
      "West-coast lagoons calm enough to swim any time of day",
      "Chamarel's seven-coloured earth and a rum distillery stop",
      "Île aux Cerfs by boat for a day away from the resort",
      "A genuinely relaxed pace — this isn't a sightseeing-heavy trip",
    ],
    faqs: [
      {
        question: "Is Mauritius only worth it for honeymoons?",
        answer:
          "It's a strong honeymoon pick, but families and groups do well here too — most resorts have a kids' club and the lagoons are shallow and calm.",
      },
    ],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 9,
    status: "published",
  },
  {
    name: "Sri Lanka",
    slug: "sri-lanka",
    aliases: [],
    country: "Sri Lanka",
    countryCode: "LK",
    region: "South Asia",
    type: "country",
    scope: "international",
    themes: ["family", "wildlife", "beach", "weekend"],
    summary: "Beaches, tea country and a leopard-sighting national park within a short flight from most Indian cities.",
    description:
      "Sri Lanka packs beaches, hill-country tea estates, ancient rock fortresses and a genuine shot at a leopard sighting in Yala National Park into a trip that's often shorter and cheaper to reach than people expect. We usually route south coast beaches with a couple of nights in the hills rather than picking just one.",
    heroImage: img("photo-1586183189334-1596e7ec6f30", "Sigiriya rock fortress rising above the jungle"),
    gallery: [img("photo-1546708770-599834c1a1e6", "Sri Lankan hill-country tea terraces")],
    startingPriceINR: 45000,
    recommendedDurationDays: 6,
    bestMonths: ["Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "Sri Lankan Rupee (LKR)",
    languages: ["Sinhala", "Tamil", "English"],
    timezone: "GMT+5:30",
    visaNote: "Electronic Travel Authorisation (ETA) required in advance; usually approved within a day.",
    coordinates: { lat: 7.8731, lng: 80.7718 },
    highlights: [
      "Sigiriya rock fortress at sunrise, before the day-trip crowds",
      "A safari in Yala National Park with a real shot at a leopard",
      "Tea-estate stays in the cool hill country around Nuwara Eliya",
      "South-coast beaches for the last two or three days",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 10,
    status: "published",
  },
  {
    name: "Turkey",
    slug: "turkey",
    aliases: [],
    country: "Turkey",
    countryCode: "TR",
    region: "Eastern Mediterranean",
    type: "country",
    scope: "international",
    themes: ["honeymoon", "family", "luxury"],
    summary: "Cappadocia's balloon-lit sunrises, Istanbul's two continents, and a coastline that rewards slowing down.",
    description:
      "Turkey usually means Istanbul and Cappadocia, and both earn the hype — Istanbul for a city that genuinely straddles Europe and Asia, Cappadocia for the hot-air balloons over the valleys at sunrise. Add a couple of nights on the Aegean or Turquoise coast if the itinerary allows, since it's a completely different pace from the two headline stops.",
    heroImage: img("photo-1524231757912-21f4fe3a7200", "Hot-air balloons over Cappadocia at sunrise"),
    gallery: [img("photo-1524231757912-21f4fe3a7200", "Cappadocia's fairy chimneys at dawn")],
    startingPriceINR: 95000,
    recommendedDurationDays: 7,
    bestMonths: ["Apr", "May", "Sep", "Oct"],
    currencyUsed: "Turkish Lira (TRY)",
    languages: ["Turkish"],
    timezone: "GMT+3",
    visaNote: "e-Visa available online for Indian passport holders, usually issued within 24 hours.",
    coordinates: { lat: 41.0082, lng: 28.9784 },
    highlights: [
      "A hot-air balloon sunrise over Cappadocia's valleys",
      "Istanbul's Hagia Sophia, Blue Mosque and the Bosphorus by boat",
      "Pamukkale's white travertine terraces",
      "A slower two or three nights on the Aegean coast",
    ],
    faqs: [
      {
        question: "Is the hot-air balloon ride actually worth booking in advance?",
        answer:
          "Yes — flights are weather-dependent and sell out in peak season, so we book it as soon as your Cappadocia dates are confirmed, not on arrival.",
      },
    ],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: true,
    displayOrder: 11,
    status: "published",
  },
  {
    name: "Europe",
    slug: "europe",
    aliases: [],
    country: "Europe",
    countryCode: "EU",
    region: "Europe",
    type: "region",
    scope: "international",
    themes: ["honeymoon", "luxury", "group"],
    summary: "A starting point for multi-country trips — Italy, France, Switzerland and beyond, planned as one itinerary.",
    description:
      "\"Europe\" isn't a single destination — it's a shorthand for the multi-country trips we build most often: Paris and the French countryside, the Swiss Alps, Italy's cities, or a Balkans route that most people haven't tried yet. Tell us the countries you're drawn to and we'll build the routing, trains and visas around it.",
    heroImage: img("photo-1499856871958-5b9627545d1a", "A European old-town square at golden hour"),
    gallery: [img("photo-1467269204594-9661b134dd2b", "Alpine mountains and a lake in Switzerland")],
    startingPriceINR: 180000,
    recommendedDurationDays: 10,
    bestMonths: ["May", "Jun", "Sep"],
    currencyUsed: "Euro (EUR) / Pound Sterling (GBP) — varies by country",
    languages: ["Varies by country"],
    timezone: "GMT+1 to GMT+3",
    visaNote: "A Schengen visa covers most mainland-Europe itineraries; UK requires a separate visa. Apply at least 15 working days ahead.",
    coordinates: { lat: 48.8566, lng: 2.3522 },
    highlights: [
      "Multi-country routing planned as one itinerary, not separate trips",
      "Rail passes and connections handled so you're not re-booking mid-trip",
      "One Schengen visa application for most mainland routes",
      "Built around the countries you actually want, not a fixed template",
    ],
    faqs: [
      {
        question: "How many countries can we realistically cover?",
        answer:
          "For a 10-12 day trip, two to three countries with real time in each — trying to fit in more usually means a lot of packing and unpacking and not much else.",
      },
    ],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 12,
    status: "published",
  },

  /* ---------------------------- Travel-list only --------------------------- */

  {
    name: "South Korea",
    slug: "south-korea",
    aliases: ["Korea"],
    country: "South Korea",
    countryCode: "KR",
    region: "East Asia",
    type: "country",
    scope: "international",
    themes: ["family", "solo", "luxury"],
    summary: "Seoul's palaces and night markets, with Busan's coastline an easy train ride away.",
    description:
      "Seoul is the draw — palaces, hanok villages, and a night market and café scene that runs late — but a Korea trip earns its extra days once you add a KTX ride down to Busan's beaches and seafood markets. We plan most itineraries around that two-city split.",
    heroImage: img("photo-1517154421773-0529f29ea451", "Gyeongbokgung Palace against the Seoul skyline"),
    gallery: [img("photo-1533628635777-112b2239b1c7", "A traditional hanok village alley in Seoul")],
    startingPriceINR: 105000,
    recommendedDurationDays: 6,
    bestMonths: ["Mar", "Apr", "Sep", "Oct"],
    currencyUsed: "South Korean Won (KRW)",
    languages: ["Korean"],
    timezone: "GMT+9",
    visaNote: "Visa required in advance for Indian passport holders; the K-ETA does not apply to Indian nationals.",
    coordinates: { lat: 37.5665, lng: 126.978 },
    highlights: [
      "Gyeongbokgung Palace and the Bukchon Hanok Village",
      "Myeongdong and Hongdae for street food and shopping",
      "A KTX day trip (or overnight) to Busan's beaches",
      "DMZ tour for a very different side of the trip",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Philippines",
    slug: "philippines",
    aliases: [],
    country: "Philippines",
    countryCode: "PH",
    region: "Southeast Asia",
    type: "country",
    scope: "international",
    themes: ["beach", "honeymoon", "adventure"],
    summary: "Island-hopping built around Palawan and Cebu, for travellers who want a genuinely quiet beach.",
    description:
      "The Philippines rewards travellers willing to island-hop — El Nido and Coron in Palawan for lagoons and shipwreck diving, or Cebu and Bohol for a mix of beaches and the Chocolate Hills. Domestic flights between islands are short but need building into the schedule properly, which is most of what we plan around.",
    heroImage: img("photo-1518509562904-e7ef99cddff9", "A limestone lagoon in Palawan"),
    gallery: [img("photo-1552465011-b4e21bf6e79a", "A traditional bangka boat over clear water")],
    startingPriceINR: 75000,
    recommendedDurationDays: 7,
    bestMonths: ["Dec", "Jan", "Feb", "Mar", "Apr"],
    currencyUsed: "Philippine Peso (PHP)",
    languages: ["Filipino", "English"],
    timezone: "GMT+8",
    visaNote: "Visa-free entry for Indian passport holders holding a valid US, UK, Schengen or Japan visa; otherwise a visa is required.",
    coordinates: { lat: 14.5995, lng: 120.9842 },
    highlights: [
      "El Nido's lagoons by island-hopping boat tour",
      "Coron's shipwreck diving and hot springs",
      "Bohol's Chocolate Hills and tarsier sanctuary",
      "Genuinely quiet beaches away from the Boracay crowds",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Saudi Arabia",
    slug: "saudi-arabia",
    aliases: [],
    country: "Saudi Arabia",
    countryCode: "SA",
    region: "Middle East",
    type: "country",
    scope: "international",
    themes: ["family", "luxury"],
    summary: "AlUla's carved tombs, Riyadh's new skyline, and a tourist e-visa that's opened the country up since 2019.",
    description:
      "Saudi Arabia only opened to leisure tourism in 2019, so it's still genuinely uncrowded — AlUla's Nabataean tombs at Hegra, Riyadh's rapidly changing skyline, and the Red Sea coast around Jeddah. We plan these as standard leisure itineraries; if your trip is specifically for Umrah or Hajj, tell us and we'll route you to the right specialist process instead.",
    heroImage: img("photo-1591604129939-f1efa4d9f7fa", "Carved rock tombs at Hegra, AlUla"),
    gallery: [img("photo-1578894381163-e72c17f2d45f", "Riyadh's skyline at dusk")],
    startingPriceINR: 90000,
    recommendedDurationDays: 6,
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "Saudi Riyal (SAR)",
    languages: ["Arabic"],
    timezone: "GMT+3",
    visaNote: "e-Visa available online for Indian passport holders for tourism; a separate process applies for Umrah/Hajj travel.",
    coordinates: { lat: 24.7136, lng: 46.6753 },
    highlights: [
      "AlUla's Nabataean tombs at Hegra, Saudi's first UNESCO site",
      "Riyadh's Edge of the World viewpoint",
      "Jeddah's historic Al-Balad district",
      "A country still genuinely uncrowded for leisure travel",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Hong Kong",
    slug: "hong-kong",
    aliases: [],
    country: "Hong Kong",
    countryCode: "HK",
    region: "East Asia",
    type: "country",
    scope: "international",
    themes: ["family", "weekend", "luxury"],
    summary: "A dense, walkable skyline with Disneyland, the Peak Tram, and dim sum worth planning meals around.",
    description:
      "Hong Kong works well as a short trip — the Peak Tram and Victoria Harbour skyline on one side, Lantau Island's Big Buddha and cable car on the other, and dim sum worth building a whole afternoon around in between. It's also an easy add-on to a longer Southeast Asia itinerary given the flight connections.",
    heroImage: img("photo-1536599424071-0b215a388ba7", "Victoria Harbour skyline at night"),
    gallery: [img("photo-1536599018102-9f803c140fc1", "The Peak Tram climbing above Hong Kong")],
    startingPriceINR: 65000,
    recommendedDurationDays: 4,
    bestMonths: ["Oct", "Nov", "Dec", "Mar"],
    currencyUsed: "Hong Kong Dollar (HKD)",
    languages: ["Cantonese", "English"],
    timezone: "GMT+8",
    visaNote: "Visa-free entry for Indian passport holders for stays up to 14 days.",
    coordinates: { lat: 22.3193, lng: 114.1694 },
    highlights: [
      "Victoria Peak at sunset, tram both ways",
      "Lantau Island's Big Buddha and the Ngong Ping cable car",
      "Dim sum in a proper Cantonese teahouse, not a tourist version",
      "Disneyland or Ocean Park as an easy family add-on day",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Oman",
    slug: "oman",
    aliases: [],
    country: "Oman",
    countryCode: "OM",
    region: "Middle East",
    type: "country",
    scope: "international",
    themes: ["adventure", "family", "solo"],
    summary: "Wadis, dunes and a mountain fjord, without Dubai's density — a quieter Gulf trip.",
    description:
      "Oman is the Gulf trip for people who want the desert and mountain scenery without Dubai's density — Wadi Shab's turquoise pools, the Sharqiya Sands for an overnight desert camp, and Musandam's fjord-like coastline by dhow boat. Muscat itself stays low-rise and relaxed, which sets the tone for the whole trip.",
    heroImage: img("photo-1595815771614-ade5bcbf3862", "Turquoise pools in Wadi Shab, Oman"),
    gallery: [img("photo-1554755229-ca4470e07232", "Desert dunes in the Sharqiya Sands")],
    startingPriceINR: 70000,
    recommendedDurationDays: 6,
    bestMonths: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "Omani Rial (OMR)",
    languages: ["Arabic", "English"],
    timezone: "GMT+4",
    visaNote: "e-Visa available online for Indian passport holders, usually processed within a few days.",
    coordinates: { lat: 23.588, lng: 58.3829 },
    highlights: [
      "Wadi Shab's hike-in turquoise pools",
      "An overnight desert camp in the Sharqiya Sands",
      "Musandam's fjord coastline by traditional dhow",
      "Muscat's low-rise, unhurried old town",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Azerbaijan",
    slug: "azerbaijan",
    aliases: [],
    country: "Azerbaijan",
    countryCode: "AZ",
    region: "Caucasus",
    type: "country",
    scope: "international",
    themes: ["honeymoon", "adventure", "weekend"],
    summary: "Baku's flame-shaped skyline and mud volcanoes, an increasingly popular short-haul pick.",
    description:
      "Baku's Old City sits directly against the futuristic Flame Towers, which is most of the city's appeal in one view. Outside the capital, Gobustan's mud volcanoes and rock carvings and the mountain town of Sheki make for an easy few days beyond the skyline.",
    heroImage: img("photo-1601074231509-8d5c9ee7e5e5", "Baku's Flame Towers at dusk"),
    gallery: [img("photo-1595184670517-f4dc9fe6a7e6", "The Old City walls of Baku")],
    startingPriceINR: 60000,
    recommendedDurationDays: 5,
    bestMonths: ["Apr", "May", "Sep", "Oct"],
    currencyUsed: "Azerbaijani Manat (AZN)",
    languages: ["Azerbaijani"],
    timezone: "GMT+4",
    visaNote: "e-Visa (ASAN Visa) available online for Indian passport holders, typically issued within 3 working days.",
    coordinates: { lat: 40.4093, lng: 49.8671 },
    highlights: [
      "Baku's Old City against the Flame Towers skyline",
      "Gobustan's mud volcanoes and prehistoric rock carvings",
      "Sheki's caravanserai and mountain scenery",
      "An easy, uncrowded short-haul pick",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Qatar",
    slug: "qatar",
    aliases: [],
    country: "Qatar",
    countryCode: "QA",
    region: "Middle East",
    type: "country",
    scope: "international",
    themes: ["family", "luxury", "weekend"],
    summary: "Doha as a stopover or a short break in its own right — museums, souks and desert safaris.",
    description:
      "Doha works well either as a stopover en route to Europe or as a short break on its own — the Museum of Islamic Art, Souq Waqif in the evening, and a desert safari out to the Inland Sea. It's compact enough to see properly in three or four days.",
    heroImage: img("photo-1548786811-dd6e453ccca7", "Doha's skyline across the Corniche"),
    gallery: [img("photo-1583417319070-4a69db38a482", "Souq Waqif lit up in the evening")],
    startingPriceINR: 62000,
    recommendedDurationDays: 4,
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "Qatari Riyal (QAR)",
    languages: ["Arabic", "English"],
    timezone: "GMT+3",
    visaNote: "Visa-free entry for Indian passport holders for stays up to 30 days.",
    coordinates: { lat: 25.2854, lng: 51.531 },
    highlights: [
      "The Museum of Islamic Art on the Corniche",
      "Souq Waqif's lanes, best walked after sunset",
      "A desert safari out to the Inland Sea",
      "Compact enough for a genuine long weekend",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "United States",
    slug: "united-states",
    aliases: ["USA", "US"],
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "country",
    scope: "international",
    themes: ["family", "luxury", "solo", "group"],
    summary: "From New York to the national parks — a country big enough that the itinerary is the whole planning problem.",
    description:
      "The US is less one destination than a dozen different trips depending on what you're after — New York and the East Coast, California's coast road, or a national-parks route through the West. The planning work is mostly about not trying to fit too much in; distances here are larger than they look on a map.",
    heroImage: img("photo-1496442226666-8d4d0e62e6e9", "The New York City skyline at dusk"),
    gallery: [img("photo-1501594907352-04cda38ebc29", "A national park landscape in the American West")],
    startingPriceINR: 210000,
    recommendedDurationDays: 10,
    bestMonths: ["Apr", "May", "Sep", "Oct"],
    currencyUsed: "US Dollar (USD)",
    languages: ["English"],
    timezone: "GMT-5 to GMT-8 (varies by region)",
    visaNote: "A B1/B2 tourist visa is required in advance; interview wait times vary by consulate.",
    coordinates: { lat: 40.7128, lng: -74.006 },
    highlights: [
      "New York's museums, neighbourhoods and skyline",
      "California's Pacific Coast Highway",
      "A national-parks route through the American West",
      "Distances planned realistically, not on paper only",
    ],
    faqs: [
      {
        question: "How far in advance should we apply for the US visa?",
        answer:
          "As early as possible — interview appointment availability varies a lot by city and season, and we'll flag realistic timelines once you tell us where you'd be applying from.",
      },
    ],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },

  /* -------------------------------- UAE cities ------------------------------ */

  {
    name: "Ras Al Khaimah",
    slug: "ras-al-khaimah",
    aliases: ["RAK"],
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    type: "emirate",
    parentSlug: "united-arab-emirates",
    scope: "international",
    themes: ["adventure", "family", "weekend"],
    summary: "The UAE's adventure emirate — Jais mountain zipline, quiet beaches, and far less traffic than Dubai.",
    description:
      "Ras Al Khaimah is the UAE's outdoors emirate — Jebel Jais has the world's longest zipline and a mountain road worth the drive on its own, and the coastline stays noticeably quieter than Dubai's. It works well either as a full trip or a two-night add-on to a Dubai itinerary.",
    heroImage: img("photo-1580418827493-f2b22c0a76cb", "Jebel Jais mountains in Ras Al Khaimah"),
    gallery: [img("photo-1512632578888-169bbbc64f33", "A quiet beach in Ras Al Khaimah")],
    startingPriceINR: 50000,
    recommendedDurationDays: 3,
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "UAE Dirham (AED)",
    languages: ["Arabic", "English"],
    timezone: "GMT+4",
    visaNote: "Visa on arrival / e-visa for most Indian passport holders with a valid US/UK/EU visa or via sponsored visa.",
    coordinates: { lat: 25.7895, lng: 55.9432 },
    highlights: [
      "The Jais Flight zipline on Jebel Jais",
      "A mountain drive with genuinely dramatic views",
      "Quieter beaches than Dubai's, at a fraction of the crowd",
      "An easy two- or three-night add-on to a Dubai trip",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Sharjah",
    slug: "sharjah",
    aliases: [],
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    type: "emirate",
    parentSlug: "united-arab-emirates",
    scope: "international",
    themes: ["family", "weekend"],
    summary: "The UAE's culture-first emirate — museums, heritage souks, and a genuinely different pace to Dubai.",
    description:
      "Sharjah leans into museums and heritage rather than skyline and shopping — the Sharjah Museum of Islamic Civilization, the restored Heart of Sharjah old quarter, and Al Noor Island in the evening. It's a short drive from Dubai, which makes it easy to add on rather than book as a standalone trip.",
    heroImage: img("photo-1601749176073-2d9c9db4e9cd", "A heritage building in Sharjah's old quarter"),
    gallery: [img("photo-1518684079-3c830dcef090", "A desert dune near Sharjah at sunset")],
    startingPriceINR: 48000,
    recommendedDurationDays: 3,
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "UAE Dirham (AED)",
    languages: ["Arabic", "English"],
    timezone: "GMT+4",
    visaNote: "Visa on arrival / e-visa for most Indian passport holders with a valid US/UK/EU visa or via sponsored visa.",
    coordinates: { lat: 25.3463, lng: 55.4209 },
    highlights: [
      "The Sharjah Museum of Islamic Civilization",
      "The restored Heart of Sharjah heritage quarter",
      "Al Noor Island's gardens and butterfly house",
      "A short, easy add-on to a Dubai itinerary",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Abu Dhabi",
    slug: "abu-dhabi",
    aliases: [],
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    type: "emirate",
    parentSlug: "united-arab-emirates",
    scope: "international",
    themes: ["family", "luxury", "weekend"],
    summary: "Sheikh Zayed Mosque, Louvre Abu Dhabi and Yas Island's theme parks, an easy pairing with Dubai.",
    description:
      "Abu Dhabi is quieter and more spread out than Dubai, built around the Sheikh Zayed Grand Mosque, Louvre Abu Dhabi on Saadiyat Island, and Yas Island's theme parks for families. Most of our itineraries pair it with Dubai as a two-city UAE trip rather than booking it alone.",
    heroImage: img("photo-1512632578888-169bbbc64f33", "Sheikh Zayed Grand Mosque at dusk"),
    gallery: [img("photo-1580418827493-f2b22c0a76cb", "Louvre Abu Dhabi's dome ceiling")],
    startingPriceINR: 58000,
    recommendedDurationDays: 3,
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "UAE Dirham (AED)",
    languages: ["Arabic", "English"],
    timezone: "GMT+4",
    visaNote: "Visa on arrival / e-visa for most Indian passport holders with a valid US/UK/EU visa or via sponsored visa.",
    coordinates: { lat: 24.4539, lng: 54.3773 },
    highlights: [
      "Sheikh Zayed Grand Mosque, best visited near sunset",
      "Louvre Abu Dhabi on Saadiyat Island",
      "Yas Island's theme parks — Ferrari World, Yas Waterworld",
      "Easily paired with Dubai as a two-city trip",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Taiwan",
    slug: "taiwan",
    aliases: [],
    country: "Taiwan",
    countryCode: "TW",
    region: "East Asia",
    type: "country",
    scope: "international",
    themes: ["family", "solo", "adventure"],
    summary: "Taipei's night markets, Taroko Gorge's marble cliffs, and a high-speed rail line that ties it together.",
    description:
      "Taipei's night markets are the obvious draw, but Taiwan's high-speed rail makes it easy to add Taroko Gorge's marble canyon in the east or Sun Moon Lake in the centre without much lost time in transit. It's an underrated pick for travellers who've already done the more obvious East Asia stops.",
    heroImage: img("photo-1470004914212-05527e49370b", "Taipei 101 rising above the city skyline"),
    gallery: [img("photo-1470004914212-05527e49370b", "Taroko Gorge's marble cliffs in Taiwan")],
    startingPriceINR: 80000,
    recommendedDurationDays: 6,
    bestMonths: ["Oct", "Nov", "Mar", "Apr"],
    currencyUsed: "New Taiwan Dollar (TWD)",
    languages: ["Mandarin Chinese"],
    timezone: "GMT+8",
    visaNote: "Visa-free entry for Indian passport holders holding a valid US, UK, Schengen, Japan, Australia, Canada or Korea visa, subject to online registration.",
    coordinates: { lat: 25.033, lng: 121.5654 },
    highlights: [
      "Taipei's night markets — Shilin and Raohe both worth a visit",
      "Taroko Gorge's marble canyon by high-speed rail",
      "Sun Moon Lake's cable car and cycling paths",
      "An underrated add-on to a wider East Asia trip",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },

  /* -------------------------- Hotel-collection only -------------------------- */

  {
    name: "Canada",
    slug: "canada",
    aliases: [],
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    type: "country",
    scope: "international",
    themes: ["family", "adventure", "wildlife"],
    summary: "Banff's mountain lakes, Niagara Falls, and cities that feel unhurried compared to their US neighbours.",
    description:
      "Canada's trips tend to split between the Rockies — Banff and Lake Louise's glacier-fed lakes — and the Toronto/Niagara/Quebec City eastern route. Both are real, separate trips more than they are one itinerary; we plan around whichever draws you more rather than trying to force both into one visit.",
    heroImage: img("photo-1503614472-8c93d56e92ce", "Lake Louise with the Rocky Mountains behind it"),
    gallery: [img("photo-1519832979-6fa011b87667", "Niagara Falls seen from the Canadian side")],
    startingPriceINR: 195000,
    recommendedDurationDays: 9,
    bestMonths: ["Jun", "Jul", "Aug", "Sep"],
    currencyUsed: "Canadian Dollar (CAD)",
    languages: ["English", "French"],
    timezone: "GMT-5 to GMT-8 (varies by region)",
    visaNote: "A visitor visa or eTA is required depending on your existing travel history; processing times vary.",
    coordinates: { lat: 51.4968, lng: -115.9281 },
    highlights: [
      "Lake Louise and Moraine Lake's glacier-fed colour",
      "The Icefields Parkway between Banff and Jasper",
      "Niagara Falls from the Canadian side",
      "Quebec City's old town for a European-feeling detour",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 101,
    status: "published",
  },
  {
    name: "Egypt",
    slug: "egypt",
    aliases: [],
    country: "Egypt",
    countryCode: "EG",
    region: "North Africa",
    type: "country",
    scope: "international",
    themes: ["family", "adventure", "solo"],
    summary: "The Pyramids of Giza, a Nile cruise between Luxor and Aswan, and Red Sea diving to unwind afterwards.",
    description:
      "Cairo and Giza are usually the first two or three days, then a Nile cruise between Luxor and Aswan for the temple sites that are genuinely worth the early starts. A few days on the Red Sea coast afterwards is a good way to end the trip at a slower pace.",
    heroImage: img("photo-1568322445389-f64ac2515020", "The Pyramids of Giza at sunset"),
    gallery: [img("photo-1590133324406-d47c8ddb772f", "A felucca sailing on the Nile near Luxor")],
    startingPriceINR: 92000,
    recommendedDurationDays: 8,
    bestMonths: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "Egyptian Pound (EGP)",
    languages: ["Arabic"],
    timezone: "GMT+2",
    visaNote: "e-Visa available online for Indian passport holders; visa on arrival is also available at major airports.",
    coordinates: { lat: 29.9773, lng: 31.1325 },
    highlights: [
      "The Pyramids of Giza and the Sphinx",
      "A multi-day Nile cruise between Luxor and Aswan",
      "The Egyptian Museum and, once open, the Grand Egyptian Museum",
      "Red Sea days on the coast to close out the trip",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 102,
    status: "published",
  },
  {
    name: "France",
    slug: "france",
    aliases: [],
    country: "France",
    countryCode: "FR",
    region: "Western Europe",
    type: "country",
    scope: "international",
    themes: ["honeymoon", "luxury", "family"],
    summary: "Paris beyond the Eiffel Tower queue, and a countryside — Loire Valley, Provence — worth the extra nights.",
    description:
      "Paris is almost always the anchor, and it earns it — but the trips that come back well-reviewed usually add three or four days outside the city too, whether that's Loire Valley châteaux, Provence's lavender season, or the French Riviera. We plan the Paris days around actual opening hours and pre-booked entry, not queue-and-hope.",
    heroImage: img("photo-1502602898657-3e91760cbb34", "The Eiffel Tower at dusk"),
    gallery: [img("photo-1499856871958-5b9627545d1a", "A château in the Loire Valley")],
    startingPriceINR: 165000,
    recommendedDurationDays: 8,
    bestMonths: ["Apr", "May", "Jun", "Sep"],
    currencyUsed: "Euro (EUR)",
    languages: ["French"],
    timezone: "GMT+1",
    visaNote: "Schengen visa required in advance; apply at least 15 working days before travel.",
    coordinates: { lat: 48.8566, lng: 2.3522 },
    highlights: [
      "Pre-booked entry to the Louvre and the Eiffel Tower, skipping the queue",
      "A day or two in the Loire Valley's châteaux",
      "Provence's lavender fields, in season",
      "The French Riviera as an optional extension",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 103,
    status: "published",
  },
  {
    name: "Moscow",
    slug: "moscow",
    aliases: [],
    country: "Russia",
    countryCode: "RU",
    region: "Eastern Europe",
    type: "city",
    parentSlug: "russia",
    scope: "international",
    themes: ["luxury", "solo", "family"],
    summary: "Red Square, the Kremlin, and a metro system worth riding just for the architecture.",
    description:
      "Moscow's headline sights — Red Square, the Kremlin, St Basil's Cathedral — sit within walking distance of each other, and the metro stations themselves (Komsomolskaya especially) are worth a detour for the architecture alone. It's a compact city core once you're past the sightseeing basics.",
    heroImage: img("photo-1513326738677-b964603b136d", "St Basil's Cathedral on Red Square"),
    gallery: [img("photo-1520106212299-d99c443e4568", "The Kremlin walls at dusk")],
    startingPriceINR: 98000,
    recommendedDurationDays: 5,
    bestMonths: ["May", "Jun", "Jul", "Aug", "Sep"],
    currencyUsed: "Russian Ruble (RUB)",
    languages: ["Russian"],
    timezone: "GMT+3",
    visaNote: "A visa is required in advance for Indian passport holders; requirements and processing times vary — check current guidance before booking flights.",
    coordinates: { lat: 55.7558, lng: 37.6173 },
    highlights: [
      "Red Square and St Basil's Cathedral",
      "A guided tour inside the Kremlin walls",
      "The architecture of the older Moscow metro stations",
      "The Bolshoi Theatre, if a performance lines up with your dates",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 104,
    status: "published",
  },
  {
    name: "Netherlands",
    slug: "netherlands",
    aliases: ["Holland"],
    country: "Netherlands",
    countryCode: "NL",
    region: "Western Europe",
    type: "country",
    scope: "international",
    themes: ["honeymoon", "family", "solo"],
    summary: "Amsterdam's canals, and a countryside of tulip fields and windmills a short train ride away.",
    description:
      "Amsterdam's canal rings and museum quarter (the Rijksmuseum and Van Gogh Museum, both worth pre-booking) are the city trip; a day trip to Keukenhof in tulip season or the windmills at Kinderdijk rounds it out without needing to change hotels.",
    heroImage: img("photo-1534351590666-13e3e96b5017", "Amsterdam's canal houses at dusk"),
    gallery: [img("photo-1534430480872-3498386e7856", "Tulip fields near Keukenhof")],
    startingPriceINR: 150000,
    recommendedDurationDays: 5,
    bestMonths: ["Apr", "May", "Jun"],
    currencyUsed: "Euro (EUR)",
    languages: ["Dutch"],
    timezone: "GMT+1",
    visaNote: "Schengen visa required in advance; apply at least 15 working days before travel.",
    coordinates: { lat: 52.3676, lng: 4.9041 },
    highlights: [
      "Amsterdam's canal rings by boat and on foot",
      "The Rijksmuseum and Van Gogh Museum, pre-booked",
      "Keukenhof's tulip fields, in season",
      "Kinderdijk's windmills as an easy half-day trip",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 105,
    status: "published",
  },
  {
    name: "Spain",
    slug: "spain",
    aliases: [],
    country: "Spain",
    countryCode: "ES",
    region: "Southern Europe",
    type: "country",
    scope: "international",
    themes: ["honeymoon", "luxury", "group"],
    summary: "Barcelona's Gaudí architecture, Madrid's museums, and a food scene worth building the schedule around.",
    description:
      "Barcelona and Madrid are genuinely different cities — Gaudí's Sagrada Família and Park Güell versus the Prado and a more traditional old-town feel — and most itineraries split time across both rather than choosing one. Meal times run late here, which is worth planning around rather than fighting.",
    heroImage: img("photo-1583422409516-2895a77efded", "The Sagrada Família in Barcelona"),
    gallery: [img("photo-1539037116277-4db20889f2d4", "A Madrid plaza at golden hour")],
    startingPriceINR: 155000,
    recommendedDurationDays: 8,
    bestMonths: ["Apr", "May", "Jun", "Sep", "Oct"],
    currencyUsed: "Euro (EUR)",
    languages: ["Spanish"],
    timezone: "GMT+1",
    visaNote: "Schengen visa required in advance; apply at least 15 working days before travel.",
    coordinates: { lat: 41.3874, lng: 2.1686 },
    highlights: [
      "Gaudí's Sagrada Família and Park Güell in Barcelona",
      "The Prado and Retiro Park in Madrid",
      "Late dinners and tapas, planned in rather than rushed",
      "An easy add-on to Seville or the Costa del Sol",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 106,
    status: "published",
  },
  {
    name: "United Kingdom",
    slug: "united-kingdom",
    aliases: ["UK"],
    country: "United Kingdom",
    countryCode: "GB",
    region: "Western Europe",
    type: "country",
    scope: "international",
    themes: ["family", "luxury", "solo"],
    summary: "London's museums and West End, with the Cotswolds or Edinburgh an easy rail trip beyond the city.",
    description:
      "London anchors most UK trips — the free national museums, a West End show, and neighbourhoods worth walking rather than only touring by bus. A couple of nights in the Cotswolds or a train up to Edinburgh adds real contrast without complicating the logistics much.",
    heroImage: img("photo-1513635269975-59663e0ac1ad", "The London skyline with Tower Bridge"),
    gallery: [img("photo-1533929736458-ca588d08c8be", "A Cotswolds village in the English countryside")],
    startingPriceINR: 175000,
    recommendedDurationDays: 8,
    bestMonths: ["May", "Jun", "Jul", "Sep"],
    currencyUsed: "Pound Sterling (GBP)",
    languages: ["English"],
    timezone: "GMT+0 (GMT+1 in summer)",
    visaNote: "A UK visa is required in advance for Indian passport holders and is separate from the Schengen visa.",
    coordinates: { lat: 51.5072, lng: -0.1276 },
    highlights: [
      "London's free national museums and a West End show",
      "The Tower of London and Tower Bridge",
      "A couple of nights in the Cotswolds' honey-stone villages",
      "Edinburgh as an easy add-on by train",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 107,
    status: "published",
  },
  {
    name: "Italy",
    slug: "italy",
    aliases: [],
    country: "Italy",
    countryCode: "IT",
    region: "Southern Europe",
    type: "country",
    scope: "international",
    themes: ["honeymoon", "luxury", "family"],
    summary: "Rome's ruins, Venice's canals and Florence's art, threaded together by a fast, reliable rail line.",
    description:
      "Rome, Florence and Venice remain the classic route because the train connections between them are genuinely fast and reliable, and each city earns its own two or three days — Rome for the Colosseum and Vatican, Florence for the Renaissance art, Venice for getting deliberately lost in the smaller canals away from San Marco.",
    heroImage: img("photo-1552832230-c0197dd311b5", "The Colosseum in Rome at golden hour"),
    gallery: [img("photo-1523906834658-6e24ef2386f9", "A gondola on a quiet Venice canal")],
    startingPriceINR: 170000,
    recommendedDurationDays: 9,
    bestMonths: ["Apr", "May", "Sep", "Oct"],
    currencyUsed: "Euro (EUR)",
    languages: ["Italian"],
    timezone: "GMT+1",
    visaNote: "Schengen visa required in advance; apply at least 15 working days before travel.",
    coordinates: { lat: 41.9028, lng: 12.4964 },
    highlights: [
      "The Colosseum and Vatican Museums in Rome, pre-booked",
      "Florence's Uffizi Gallery and the Duomo",
      "Venice's quieter canals, away from San Marco",
      "Fast, reliable trains between all three cities",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: false,
    displayOrder: 108,
    status: "published",
  },

  /* ------------------------- Parent/hierarchy records ------------------------ */

  {
    name: "United Arab Emirates",
    slug: "united-arab-emirates",
    aliases: ["UAE"],
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    type: "country",
    scope: "international",
    themes: ["family", "luxury", "weekend"],
    summary: "Seven emirates, from Dubai's skyline to Ras Al Khaimah's mountains — each with its own pace.",
    description:
      "The UAE covers seven emirates that read very differently once you're past Dubai's skyline — Abu Dhabi's museums, Sharjah's heritage quarter, and Ras Al Khaimah's mountains and beaches. Most trips still centre on Dubai, with a nearby emirate added as a day trip or overnight rather than treated as a separate booking.",
    heroImage: img("photo-1512453979798-5ea266f8880c", "Dubai skyline at sunset"),
    gallery: [img("photo-1512632578888-169bbbc64f33", "Sheikh Zayed Grand Mosque in Abu Dhabi")],
    startingPriceINR: 55000,
    recommendedDurationDays: 5,
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    currencyUsed: "UAE Dirham (AED)",
    languages: ["Arabic", "English"],
    timezone: "GMT+4",
    visaNote: "Visa on arrival / e-visa for most Indian passport holders with a valid US/UK/EU visa or via sponsored visa.",
    coordinates: { lat: 24.4667, lng: 54.3667 },
    highlights: [
      "Dubai's skyline, souks and desert camps",
      "Abu Dhabi's museums and Grand Mosque",
      "Sharjah's heritage quarter",
      "Ras Al Khaimah's mountains for an adventure add-on",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "published",
  },
  {
    name: "Russia",
    slug: "russia",
    aliases: [],
    country: "Russia",
    countryCode: "RU",
    region: "Eastern Europe",
    type: "country",
    scope: "international",
    themes: ["luxury", "solo"],
    summary: "Moscow and St Petersburg — the two-city classic, currently the extent of what we plan here.",
    description:
      "Russia trips through us today are almost always Moscow, described on its own destination page — a St Petersburg extension is possible on request, but we don't yet carry it as a standing itinerary. Check current visa and travel-advisory guidance before booking flights, since requirements have changed more often here than most destinations recently.",
    heroImage: img("photo-1513326738677-b964603b136d", "St Basil's Cathedral on Red Square, Moscow"),
    gallery: [img("photo-1520106212299-d99c443e4568", "The Kremlin walls at dusk")],
    startingPriceINR: 98000,
    recommendedDurationDays: 5,
    bestMonths: ["May", "Jun", "Jul", "Aug", "Sep"],
    currencyUsed: "Russian Ruble (RUB)",
    languages: ["Russian"],
    timezone: "GMT+3",
    visaNote: "A visa is required in advance for Indian passport holders; requirements and processing times vary — check current guidance before booking flights.",
    coordinates: { lat: 55.7558, lng: 37.6173 },
    highlights: [
      "Moscow's Red Square and the Kremlin",
      "A possible St Petersburg extension, on request",
      "Check current visa guidance before booking",
    ],
    faqs: [],
    isFeatured: false,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: false,
    displayOrder: 0,
    status: "draft",
  },
];

/* -------------------------------------------------------------------------- */
/*                 Existing destinations — safe-field backfill                */
/* -------------------------------------------------------------------------- */

export interface DestinationBackfill {
  slug: string;
  fields: {
    type?: DestinationTypeSeed;
    parentSlug?: string;
    aliases?: string[];
    hotelFeatured?: boolean;
    packageFeatured?: boolean;
    displayOrder?: number;
    isDemoData?: boolean;
  };
}

export const EXISTING_DESTINATION_BACKFILL: DestinationBackfill[] = [
  { slug: "bali", fields: { type: "region", hotelFeatured: true, packageFeatured: true, displayOrder: 5, isDemoData: true } },
  { slug: "kyoto", fields: { type: "city", isDemoData: true } },
  { slug: "santorini", fields: { type: "region", isDemoData: true } },
  { slug: "kerala-backwaters", fields: { type: "region", isDemoData: true } },
  { slug: "ladakh", fields: { type: "region", isDemoData: true } },
  {
    slug: "dubai",
    fields: {
      type: "emirate",
      parentSlug: "united-arab-emirates",
      hotelFeatured: false,
      packageFeatured: true,
      displayOrder: 4,
      isDemoData: true,
    },
  },
  { slug: "kashmir", fields: { type: "region", isDemoData: true } },
  { slug: "manali", fields: { type: "region", isDemoData: true } },
  { slug: "goa", fields: { type: "region", isDemoData: true } },
  { slug: "rajasthan", fields: { type: "region", isDemoData: true } },
  { slug: "thailand", fields: { type: "country", hotelFeatured: true, packageFeatured: true, displayOrder: 1, isDemoData: true } },
  { slug: "singapore", fields: { type: "country", hotelFeatured: true, packageFeatured: true, displayOrder: 2, isDemoData: true } },
  { slug: "malaysia", fields: { type: "country", hotelFeatured: false, packageFeatured: true, displayOrder: 8, isDemoData: true } },
  { slug: "maldives", fields: { type: "country", hotelFeatured: false, packageFeatured: true, displayOrder: 6, isDemoData: true } },
  { slug: "andaman", fields: { type: "region", isDemoData: true } },
  { slug: "vietnam", fields: { type: "country", hotelFeatured: true, packageFeatured: true, displayOrder: 3, isDemoData: true } },
];
