const extraPackages = [
  // 40. Dubai Marina & Abu Dhabi
  {
    title: "Dubai Marina & Abu Dhabi",
    slug: "dubai-marina-abu-dhabi",
    subtitle: "Burj Khalifa, desert safari, Sheikh Zayed Mosque, and more",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Dubai", "Abu Dhabi"],
    scope: "international",
    tripTypes: ["family", "leisure", "luxury"],
    collections: ["trending-international", "affordable-getaways"],
    durationDays: 5,
    durationNights: 4,
    heroImage: img("https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80", "Burj Khalifa Dubai"),
    gallery: [
      img("https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&q=80", "Dubai skyline"),
    ],
    overview: "Five days in the UAE — Burj Khalifa's panoramic views, thrilling desert safari with dune bashing, Sheikh Zayed Grand Mosque's architectural splendour.",
    highlights: ["Burj Khalifa At The Top", "Desert safari with dune bashing, BBQ, and entertainment", "Sheikh Zayed Grand Mosque", "Dubai Marina dinner cruise", "Dubai Mall and Aquarium", "Louvre Abu Dhabi"],
    itinerary: [
      { day: 1, city: "Dubai", title: "Arrival & Downtown Dubai", description: "Arrive at DXB. Transfer to hotel. Burj Khalifa. Dubai Mall.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Burj Khalifa At The Top", "Dubai Fountain show"] },
      { day: 2, city: "Dubai", title: "Desert Safari", description: "Desert safari with dune bashing, camel ride, BBQ dinner.", images: [], meals: ["breakfast", "dinner"], transfers: "Private 4x4", activities: ["Desert safari", "Dune bashing", "BBQ dinner"] },
      { day: 3, city: "Dubai → Abu Dhabi", title: "Abu Dhabi Day Trip", description: "Sheikh Zayed Grand Mosque. Louvre Abu Dhabi. Marina dinner cruise.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Sheikh Zayed Grand Mosque", "Louvre Abu Dhabi", "Marina dinner cruise"] },
      { day: 4, city: "Dubai", title: "Old Dubai & Gold Souk", description: "Jumeirah Beach. Al Fahidi Historical District. Gold Souk. Dhow cruise.", images: [], meals: ["breakfast"], transfers: "Metro + walking", activities: ["Jumeirah Beach", "Gold Souk", "Dhow cruise"] },
      { day: 5, city: "Dubai", title: "Farewell UAE", description: "Palm Jumeirah visit. Transfer to DXB.", images: [], meals: ["breakfast"], transfers: "Airport transfer", activities: ["Palm Jumeirah", "Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 4, durationDays: 5, durationNights: 4, pricePerAdultINR: 42999, pricePerChildINR: 30000, singleSupplementINR: 18000, originalPricePerAdultINR: 53999, inclusionsExtra: ["4-star hotel in Deira", "Desert safari with BBQ", "Burj Khalifa"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 5, durationDays: 5, durationNights: 4, pricePerAdultINR: 69999, pricePerChildINR: 49000, singleSupplementINR: 32000, originalPricePerAdultINR: 86999, inclusionsExtra: ["5-star hotel Marina", "VIP desert safari", "Private transfers"], isDefault: false },
    ],
    departures: makeDepartures(15, 5, 7),
    departureCities: ["Delhi", "Mumbai", "Chennai", "Kolkata"],
    startingPriceINR: 42999,
    originalPriceINR: 53999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: true,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["October", "November", "December", "January", "February", "March", "April"],
    inclusions: ["Return flights from India", "4 nights 4-star hotel", "Daily breakfast and dinner", "Burj Khalifa At The Top", "Desert safari with BBQ", "Sheikh Zayed Grand Mosque", "Louvre Abu Dhabi", "Dubai Marina dinner cruise", "All transfers", "UAE visa assistance", "Travel insurance"],
    exclusions: ["Lunch", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Oct-Apr", "Dress modestly at mosques"],
    visaDetails: "UAE visa processing included.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 10 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Dubai", name: "Citymax Hotel Bur Dubai", category: 4, nights: 4, note: "Bur Dubai" },
    ],
    faqs: [
      { question: "Is Dubai expensive?", answer: "Dining ranges from budget to luxury." },
    ],
    ratingAverage: 4.5,
    ratingCount: 380,
    isFeatured: true,
    isTrending: true,
    isBestseller: true,
    status: "published",
    seo: { title: "Dubai Marina & Abu Dhabi — 5 Days 4 Nights from 42999", description: "UAE tour package with Burj Khalifa, desert safari, Sheikh Zayed Mosque, Louvre Abu Dhabi." },
    viewCount: 10500,
    enquiryCount: 440,
    bookingCount: 310,
    deletedAt: null,
    isDemoData: true,
  },

  // 41. Sri Lanka Highlights
  {
    title: "Sri Lanka Highlights",
    slug: "sri-lanka-highlights",
    subtitle: "Ancient cities, hill country, temples, and pristine beaches",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Colombo", "Kandy", "Nuwara Eliya", "Galle"],
    scope: "international",
    tripTypes: ["culture", "family", "beach"],
    collections: ["trending-international", "best-of-india"],
    durationDays: 7,
    durationNights: 6,
    heroImage: img("https://images.unsplash.com/photo-1566837945700-30057527ade0?w=1200&q=80", "Sri Lanka temple"),
    gallery: [
      img("https://images.unsplash.com/photo-1572896382533-96b766d09fd7?w=800&q=80", "Sri Lanka tea garden"),
    ],
    overview: "Seven days in Sri Lanka — explore ancient cities, ride the scenic hill country train, visit the sacred Temple of the Tooth in Kandy.",
    highlights: ["Temple of the Tooth Relic in Kandy", "Sigiriya Lion Rock fortress", "Scenic hill country train ride", "Pinnawala Elephant Orphanage", "Galle Fort UNESCO heritage", "Yala National Park safari"],
    itinerary: [
      { day: 1, city: "Negombo", title: "Arrival in Sri Lanka", description: "Arrive at CMB. Transfer to Negombo hotel.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Negombo beach"] },
      { day: 2, city: "Negombo → Sigiriya", title: "Drive to Sigiriya", description: "Drive to Sigiriya. Sigiriya Lion Rock fortress.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Sigiriya Lion Rock"] },
      { day: 3, city: "Sigiriya → Kandy", title: "Drive to Kandy", description: "Dambulla Cave Temple. Temple of the Tooth.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Dambulla Cave Temple", "Temple of the Tooth"] },
      { day: 4, city: "Kandy → Nuwara Eliya", title: "Hill Country Train", description: "Scenic train to Nuwara Eliya. Tea plantation tour.", images: [], meals: ["breakfast"], transfers: "Train", activities: ["Hill country train", "Tea plantation"] },
      { day: 5, city: "Nuwara Eliya → Ella", title: "Ella Day Trip", description: "Train to Ella. Little Adam's Peak. Nine Arch Bridge.", images: [], meals: ["breakfast", "dinner"], transfers: "Train", activities: ["Little Adam's Peak", "Nine Arch Bridge"] },
      { day: 6, city: "Nuwara Eliya → Galle", title: "Drive to Galle", description: "Drive to Galle. Galle Fort. Unawatuna Beach.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Galle Fort", "Unawatuna Beach"] },
      { day: 7, city: "Galle → Colombo → Departure", title: "Farewell Sri Lanka", description: "Bentota Beach. Transfer to CMB.", images: [], meals: ["breakfast"], transfers: "Private car + airport", activities: ["Bentota Beach", "Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 7, durationNights: 6, pricePerAdultINR: 35999, pricePerChildINR: 25000, singleSupplementINR: 14000, originalPricePerAdultINR: 44999, inclusionsExtra: ["3-star hotels", "Hill country train", "All transfers"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 7, durationNights: 6, pricePerAdultINR: 55999, pricePerChildINR: 39000, singleSupplementINR: 22000, originalPricePerAdultINR: 69999, inclusionsExtra: ["4-star hotels", "Private car throughout"], isDefault: false },
    ],
    departures: makeDepartures(12, 4, 14),
    departureCities: ["Chennai", "Colombo"],
    startingPriceINR: 35999,
    originalPriceINR: 44999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["December", "January", "February", "March", "April", "July", "August"],
    inclusions: ["Return flights from India", "6 nights accommodation", "All transfers", "Sigiriya Lion Rock", "Dambulla Cave Temple", "Temple of the Tooth", "Hill country train", "Pinnawala Elephant Orphanage", "Galle Fort", "Travel insurance"],
    exclusions: ["Lunch", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Dec-Apr and Jul-Aug", "Dress modestly for temples"],
    visaDetails: "Sri Lanka visa on arrival for Indian passport holders.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 7 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Negombo", name: "Jetwing Beach Hotel", category: 4, nights: 1, note: "Beachfront" },
      { city: "Sigiriya", name: "Hotel Sigiriya", category: 3, nights: 1, note: "Rock view" },
      { city: "Kandy", name: "Earl's Regency Hotel", category: 4, nights: 1, note: "Lake view" },
      { city: "Nuwara Eliya", name: "Grand Hotel Nuwara Eliya", category: 4, nights: 1, note: "Heritage hotel" },
      { city: "Galle", name: "Fort Bazaar", category: 4, nights: 1, note: "Inside Galle Fort" },
    ],
    faqs: [
      { question: "Do I need a visa?", answer: "Indian passport holders get a visa on arrival — we assist." },
    ],
    ratingAverage: 4.5,
    ratingCount: 190,
    isFeatured: false,
    isTrending: false,
    isBestseller: false,
    status: "published",
    seo: { title: "Sri Lanka Highlights — 7 Days 6 Nights from 35999", description: "Sri Lanka tour with Sigiriya Lion Rock, Kandy Temple of the Tooth, hill country train and Galle Fort." },
    viewCount: 5900,
    enquiryCount: 210,
    bookingCount: 130,
    deletedAt: null,
    isDemoData: true,
  },

  // 42. Maldives Overwater Villa
  {
    title: "Maldives Overwater Villa",
    slug: "maldives-overwater-villa",
    subtitle: "Crystal-clear waters, overwater villas, and island escapes",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Male", "Maafushi"],
    scope: "international",
    tripTypes: ["honeymoon", "luxury", "beach"],
    collections: ["honeymoon-escapes", "trending-international"],
    durationDays: 5,
    durationNights: 4,
    heroImage: img("https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&q=80", "Maldives overwater villa"),
    gallery: [
      img("https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80", "Maldives resort"),
    ],
    overview: "Five days in paradise — overwater villas with glass floor panels, snorkelling among manta rays, sunset dolphin cruises.",
    highlights: ["Overwater villa with private pool", "Snorkelling at Maafushi", "Sunset dolphin cruise", "Bioluminescent plankton night swim", "Candlelit beach dinner"],
    itinerary: [
      { day: 1, city: "Male", title: "Arrival & Speedboat Transfer", description: "Arrive at MLE. Speedboat to resort. Welcome drink.", images: [], meals: ["dinner"], transfers: "Speedboat", activities: ["Villa check-in"] },
      { day: 2, city: "Maafushi", title: "Snorkelling & Water Sports", description: "House reef snorkelling. Paddleboarding. Spa session.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Resort", activities: ["Snorkelling", "Spa session"] },
      { day: 3, city: "Maafushi", title: "Full Day at Leisure", description: "Beach yoga. Infinity pool. Dolphin cruise.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Resort", activities: ["Beach yoga", "Dolphin cruise"] },
      { day: 4, city: "Maafushi", title: "Bioluminescent Plankton", description: "Sandbank picnic. Bioluminescent night swim.", images: [], meals: ["breakfast", "dinner"], transfers: "Resort boat", activities: ["Bioluminescent swim"] },
      { day: 5, city: "Male", title: "Farewell Maldives", description: "Morning spa. Speedboat to MLE. Departure.", images: [], meals: ["breakfast"], transfers: "Speedboat + airport", activities: ["Departure"] },
    ],
    variants: [
      { key: "premium", label: "Premium Overwater Villa", hotelCategory: 5, durationDays: 5, durationNights: 4, pricePerAdultINR: 134999, pricePerChildINR: 75000, singleSupplementINR: 60000, originalPricePerAdultINR: 169999, inclusionsExtra: ["Overwater villa with private pool", "Full board", "All water sports"], isDefault: true },
    ],
    departures: makeDepartures(8, 2, 14),
    departureCities: ["Delhi", "Mumbai"],
    startingPriceINR: 134999,
    originalPriceINR: 169999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 5,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["November", "December", "January", "February", "March", "April"],
    inclusions: ["Return flights from India", "4 nights overwater villa", "Speedboat transfers", "All meals and beverages", "Snorkelling equipment", "Sunset dolphin cruise", "Bioluminescent excursion", "Candlelit beach dinner", "Travel insurance"],
    exclusions: ["Seaplane upgrade", "Premium beverages", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Nov-Apr", "Book well in advance"],
    visaDetails: "Free 30-day visa on arrival for Indian passport holders.",
    cancellationPolicy: [
      { window: "More than 30 days before departure", charge: "15% of total" },
      { window: "15–30 days before departure", charge: "50% of total" },
      { window: "Less than 15 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 15 days before departure"],
    termsAndConditions: ["Prices per person on double occupancy"],
    hotels: [
      { city: "Maafushi", name: "Sun Siyam Olhuveli", category: 5, nights: 4, note: "Overwater villa" },
    ],
    faqs: [
      { question: "Are overwater villas worth it?", answer: "Absolutely — waking up over crystal-clear water is unforgettable." },
    ],
    ratingAverage: 4.9,
    ratingCount: 180,
    isFeatured: true,
    isTrending: false,
    isBestseller: false,
    status: "published",
    seo: { title: "Maldives Overwater Villa — 5 Days 4 Nights from 134999", description: "Maldives overwater villa with flights, speedboat transfer, snorkelling and dolphin cruise." },
    viewCount: 8200,
    enquiryCount: 350,
    bookingCount: 200,
    deletedAt: null,
    isDemoData: true,
  },

  // 43. Leh Ladakh Motorcycle Expedition
  {
    title: "Leh Ladakh Motorcycle Expedition",
    slug: "leh-ladakh-motorcycle-expedition",
    subtitle: "Royal Enfield ride through Khardung La, Nubra Valley, and Pangong Lake",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Leh", "Nubra Valley", "Pangong Lake", "Tso Moriri"],
    scope: "domestic",
    tripTypes: ["adventure", "leisure"],
    collections: ["adventure-tours", "best-of-india"],
    durationDays: 10,
    durationNights: 9,
    heroImage: img("https://images.unsplash.com/photo-1585137277230-b0a1b9c8a9e4?w=1200&q=80", "Ladakh motorcycle"),
    gallery: [
      img("https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80", "Pangong Lake Ladakh"),
    ],
    overview: "Ten days on Royal Enfields through the world's highest motorable roads — Khardung La, Nubra Valley's sand dunes, Pangong Lake.",
    highlights: ["Khardung La — world's highest motorable road", "Nubra Valley sand dunes and camel safari", "Pangong Lake", "Tso Moriri bird sanctuary", "Magnetic Hill", "Hemis Monastery"],
    itinerary: [
      { day: 1, city: "Leh", title: "Arrival in Leh", description: "Arrive at KLH. Transfer to hotel. Rest and acclimatisation.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Acclimatisation walk"] },
      { day: 2, city: "Leh", title: "Leh Sightseeing", description: "Shanti Stupa. Leh Palace. Hall of Fame. Magnetic Hill.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Shanti Stupa", "Leh Palace"] },
      { day: 3, city: "Leh → Nubra Valley", title: "Ride to Nubra Valley", description: "Ride over Khardung La. Deskit Monastery. Hunder sand dunes.", images: [], meals: ["breakfast", "dinner"], transfers: "Royal Enfield motorcycle", activities: ["Khardung La", "Camel ride"] },
      { day: 4, city: "Nubra Valley → Leh", title: "Return to Leh", description: "Ride back to Leh.", images: [], meals: ["breakfast"], transfers: "Royal Enfield motorcycle", activities: ["Ride back to Leh"] },
      { day: 5, city: "Leh", title: "Rest Day", description: "Rest and prepare for Pangong.", images: [], meals: ["breakfast", "dinner"], transfers: "On foot", activities: ["Leh Market"] },
      { day: 6, city: "Leh → Pangong Lake", title: "Ride to Pangong Lake", description: "Ride via Chang La pass. Overnight glamping by the lake.", images: [], meals: ["breakfast", "dinner"], transfers: "Royal Enfield motorcycle", activities: ["Chang La", "Pangong Lake sunset"] },
      { day: 7, city: "Pangong Lake", title: "Pangong Full Day", description: "Photography. Lake shore walk. Stargazing.", images: [], meals: ["breakfast", "dinner"], transfers: "On foot", activities: ["Photography", "Stargazing"] },
      { day: 8, city: "Pangong Lake → Tso Moriri", title: "Ride to Tso Moriri", description: "Korzok village. Korzok monastery.", images: [], meals: ["breakfast", "dinner"], transfers: "Royal Enfield motorcycle", activities: ["Tso Moriri"] },
      { day: 9, city: "Tso Moriri → Leh", title: "Return to Leh", description: "Ride back to Leh. Farewell dinner.", images: [], meals: ["breakfast", "dinner"], transfers: "Royal Enfield motorcycle", activities: ["Farewell dinner"] },
      { day: 10, city: "Leh", title: "Departure", description: "Transfer to airport.", images: [], meals: ["breakfast"], transfers: "Airport transfer", activities: ["Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 10, durationNights: 9, pricePerAdultINR: 38999, pricePerChildINR: 28000, singleSupplementINR: 14000, originalPricePerAdultINR: 49999, inclusionsExtra: ["3-star hotels", "Royal Enfield", "Camping at Pangong", "All fuel"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 10, durationNights: 9, pricePerAdultINR: 54999, pricePerChildINR: 39000, singleSupplementINR: 20000, originalPricePerAdultINR: 69999, inclusionsExtra: ["4-star hotels", "Royal Enfield Himalayan 410", "Glamping at Pangong"], isDefault: false },
    ],
    departures: makeDepartures(10, 4, 20),
    departureCities: ["Delhi", "Chandigarh"],
    startingPriceINR: 38999,
    originalPriceINR: 49999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["June", "July", "August", "September"],
    inclusions: ["Return flights from Leh", "9 nights accommodation", "Royal Enfield motorcycle", "Inner line permits", "All fuel", "All meals", "Camping/glamping at Pangong", "Professional riding guide", "Back-up vehicle", "Travel insurance"],
    exclusions: ["Personal expenses", "Tips"],
    importantInfo: ["Best time: Jun-Sep", "Carry warm clothing", "Acclimatisation essential"],
    visaDetails: "No visa required — domestic travel.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 10 days before departure"],
    termsAndConditions: ["Valid driving licence required", "Helmet provided"],
    hotels: [
      { city: "Leh", name: "Grand Dragon Ladakh", category: 4, nights: 5, note: "Leh city centre" },
      { city: "Nubra Valley", name: "Nubra Valley Camp", category: 3, nights: 1, note: "Deluxe tent" },
      { city: "Pangong Lake", name: "Pangong Camp", category: 3, nights: 2, note: "Swiss cottage" },
      { city: "Tso Moriri", name: "Tso Moriri Camp", category: 3, nights: 1, note: "Lake view tent" },
    ],
    faqs: [
      { question: "Do I need a bike licence?", answer: "Yes — a valid Indian driving licence is mandatory." },
    ],
    ratingAverage: 4.7,
    ratingCount: 260,
    isFeatured: true,
    isTrending: true,
    isBestseller: false,
    status: "published",
    seo: { title: "Leh Ladakh Motorcycle Expedition — 10 Days from 38999", description: "Ladakh motorcycle tour with Royal Enfield, Khardung La, Nubra Valley, Pangong Lake." },
    viewCount: 9800,
    enquiryCount: 420,
    bookingCount: 280,
    deletedAt: null,
    isDemoData: true,
  },

  // 44. Andaman Islands Escape
  {
    title: "Andaman Islands Escape",
    slug: "andaman-islands-escape",
    subtitle: "Radhanagar Beach, Cellular Jail, Snorkelling, and Scuba Diving",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Port Blair", "Havelock Island", "Neil Island"],
    scope: "domestic",
    tripTypes: ["beach", "adventure", "honeymoon"],
    collections: ["honeymoon-escapes", "trending-international"],
    durationDays: 6,
    durationNights: 5,
    heroImage: img("https://images.unsplash.com/photo-1580137187710-1c31e9e2dd17?w=1200&q=80", "Andaman beach"),
    gallery: [
      img("https://images.unsplash.com/photo-1544550583-49597d67307a?w=800&q=80", "Andaman Havelock"),
    ],
    overview: "Six days in the Andaman Islands — Asia's best beach at Radhanagar, world-class scuba diving, historic Cellular Jail.",
    highlights: ["Radhanagar Beach — Asia's best beach", "Scuba diving at Havelock", "Snorkelling at Elephant Beach", "Cellular Jail light and sound show", "Neil Island's Bharatpur Beach"],
    itinerary: [
      { day: 1, city: "Port Blair", title: "Arrival & Cellular Jail", description: "Arrive at IXZ. Visit Cellular Jail.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Cellular Jail"] },
      { day: 2, city: "Port Blair → Havelock", title: "Ferry to Havelock", description: "Ferry to Havelock. Radhanagar Beach sunset.", images: [], meals: ["breakfast"], transfers: "Government ferry", activities: ["Radhanagar Beach"] },
      { day: 3, city: "Havelock Island", title: "Scuba Diving", description: "Scuba diving at Elephant Beach. Snorkelling.", images: [], meals: ["breakfast"], transfers: "Ferry + boat", activities: ["Scuba diving", "Snorkelling"] },
      { day: 4, city: "Havelock → Neil Island", title: "Ferry to Neil", description: "Ferry to Neil Island. Bharatpur Beach.", images: [], meals: ["breakfast"], transfers: "Ferry", activities: ["Bharatpur Beach"] },
      { day: 5, city: "Neil Island", title: "Neil Full Day", description: "Natural bridge. Sitapur Beach.", images: [], meals: ["breakfast", "dinner"], transfers: "Local", activities: ["Natural Bridge"] },
      { day: 6, city: "Neil → Port Blair", title: "Return to Port Blair", description: "Ferry to Port Blair. Transfer to airport.", images: [], meals: ["breakfast"], transfers: "Ferry + airport", activities: ["Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 6, durationNights: 5, pricePerAdultINR: 28999, pricePerChildINR: 20000, singleSupplementINR: 10000, originalPricePerAdultINR: 36999, inclusionsExtra: ["3-star beach resort", "Ferry tickets", "Scuba diving"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 6, durationNights: 5, pricePerAdultINR: 42999, pricePerChildINR: 30000, singleSupplementINR: 16000, originalPricePerAdultINR: 54999, inclusionsExtra: ["4-star resort", "Multiple dives"], isDefault: false },
    ],
    departures: makeDepartures(10, 4, 7),
    departureCities: ["Chennai", "Kolkata"],
    startingPriceINR: 28999,
    originalPriceINR: 36999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["October", "November", "December", "January", "February", "March", "April"],
    inclusions: ["Return flights from India", "5 nights accommodation", "Ferry transfers", "Cellular Jail", "Scuba diving", "Snorkelling", "Radhanagar Beach", "Neil Island", "All meals", "Travel insurance"],
    exclusions: ["Seaplane upgrade", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Oct-Apr", "Voter ID sufficient for Indian nationals"],
    visaDetails: "No visa required for Indian nationals — Voter ID is sufficient.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 7 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Port Blair", name: "Peerless Resort", category: 3, nights: 2, note: "Sea-facing" },
      { city: "Havelock Island", name: "Symphony Palms Beach Resort", category: 4, nights: 1, note: "Beachfront" },
      { city: "Neil Island", name: "Summer Sand Beach Resort", category: 3, nights: 1, note: "Beachfront" },
    ],
    faqs: [
      { question: "Is a passport needed?", answer: "Indian nationals only need a Voter ID or Aadhaar card." },
    ],
    ratingAverage: 4.6,
    ratingCount: 310,
    isFeatured: false,
    isTrending: true,
    isBestseller: false,
    status: "published",
    seo: { title: "Andaman Islands Escape — 6 Days 5 Nights from 28999", description: "Andaman tour with Radhanagar Beach, Cellular Jail, scuba diving at Havelock." },
    viewCount: 7500,
    enquiryCount: 310,
    bookingCount: 210,
    deletedAt: null,
    isDemoData: true,
  },

  // 45. Kerala Backwaters & Hill Stations
  {
    title: "Kerala Backwaters & Hill Stations",
    slug: "kerala-backwaters-hill-stations",
    subtitle: "Houseboats, tea plantations, Ayurveda, and wildlife",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Kochi", "Munnar", "Thekkady", "Alleppey"],
    scope: "domestic",
    tripTypes: ["honeymoon", "family", "leisure"],
    collections: ["honeymoon-escapes", "best-of-india"],
    durationDays: 7,
    durationNights: 6,
    heroImage: img("https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80", "Kerala houseboat"),
    gallery: [
      img("https://images.unsplash.com/photo-1593693397690-362cb9666c2f?w=800&q=80", "Kerala backwaters"),
    ],
    overview: "Seven days in God's Own Country — overnight houseboat cruise through Alleppey backwaters, misty tea gardens of Munnar, Periyar wildlife sanctuary.",
    highlights: ["Overnight houseboat cruise in Alleppey backwaters", "Munnar tea gardens and Eravikulam National Park", "Periyar wildlife sanctuary boat safari", "Fort Kochi Chinese fishing nets", "Kathakali dance performance", "Traditional Ayurveda massage"],
    itinerary: [
      { day: 1, city: "Kochi", title: "Arrival in Kochi", description: "Arrive at Kochi (COK). Fort Kochi walk. Kathakali dance.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Fort Kochi", "Kathakali dance"] },
      { day: 2, city: "Kochi → Munnar", title: "Drive to Munnar", description: "Drive to Munnar (4 hrs). Spice garden. Tea plantation.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Spice garden", "Tea plantation"] },
      { day: 3, city: "Munnar", title: "Munnar Sightseeing", description: "Eravikulam National Park. Mattupetty Dam. Echo Point. Tea museum.", images: [], meals: ["breakfast", "dinner"], transfers: "Private jeep", activities: ["Eravikulam NP", "Mattupetty Dam", "Tea museum"] },
      { day: 4, city: "Munnar → Thekkady", title: "Drive to Thekkady", description: "Drive to Thekkady (3.5 hrs). Periyar wildlife safari.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Periyar wildlife safari", "Elephant ride"] },
      { day: 5, city: "Thekkady → Alleppey", title: "Houseboat Arrival", description: "Drive to Alleppey. Board houseboat. Cruise through backwaters.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Private car + houseboat", activities: ["Houseboat cruise", "Backwaters"] },
      { day: 6, city: "Alleppey", title: "Houseboat Day", description: "Full day on houseboat. Village visits.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Houseboat", activities: ["Backwaters cruise", "Village visit"] },
      { day: 7, city: "Alleppey → Kochi", title: "Return to Kochi", description: "Disembark houseboat. Drive to Kochi. Transfer to airport.", images: [], meals: ["breakfast"], transfers: "Private car + airport", activities: ["Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 7, durationNights: 6, pricePerAdultINR: 25999, pricePerChildINR: 18000, singleSupplementINR: 10000, originalPricePerAdultINR: 33999, inclusionsExtra: ["3-star hotels", "AC houseboat", "All transfers"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 7, durationNights: 6, pricePerAdultINR: 39999, pricePerChildINR: 28000, singleSupplementINR: 15000, originalPricePerAdultINR: 51999, inclusionsExtra: ["4-star resort + premium houseboat", "Ayurveda massage"], isDefault: false },
    ],
    departures: makeDepartures(12, 5, 7),
    departureCities: ["Kochi", "Trivandrum", "Bangalore"],
    startingPriceINR: 25999,
    originalPriceINR: 33999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["September", "October", "November", "December", "January", "February", "March"],
    inclusions: ["Return flights from India", "6 nights accommodation", "Overnight houseboat with AC", "Daily breakfast and dinner", "All transfers", "Fort Kochi sightseeing", "Eravikulam National Park", "Periyar wildlife safari", "Alleppey backwaters", "Travel insurance"],
    exclusions: ["Lunch", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Sep-Mar", "Book houseboat well in advance"],
    visaDetails: "No visa required for domestic travel.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 7 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Kochi", name: "Taj Malabar Resort & Spa", category: 5, nights: 1, note: "Willingdon Island" },
      { city: "Munnar", name: "Tea Valley Resort", category: 4, nights: 2, note: "Munnar tea garden view" },
      { city: "Thekkady", name: "Spice Village", category: 4, nights: 1, note: "Thekkady" },
      { city: "Alleppey", name: "Premium Houseboat", category: 4, nights: 2, note: "AC houseboat" },
    ],
    faqs: [
      { question: "Is the houseboat safe?", answer: "Yes, all our houseboats are fully licensed." },
    ],
    ratingAverage: 4.7,
    ratingCount: 410,
    isFeatured: true,
    isTrending: true,
    isBestseller: false,
    status: "published",
    seo: { title: "Kerala Backwaters & Hill Stations — 7 Days 6 Nights from 25999", description: "Kerala tour with houseboat cruise in Alleppey, Munnar tea gardens, Thekkady wildlife, Fort Kochi." },
    viewCount: 11200,
    enquiryCount: 480,
    bookingCount: 340,
    deletedAt: null,
    isDemoData: true,
  },

  // 46. Thailand Beach & Bangkok
  {
    title: "Thailand Beach & Bangkok",
    slug: "thailand-beach-bangkok",
    subtitle: "Pattaya beaches, Bangkok temples, coral island, and Thai cuisine",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Bangkok", "Pattaya"],
    scope: "international",
    tripTypes: ["beach", "family", "leisure"],
    collections: ["trending-international", "affordable-getaways"],
    durationDays: 5,
    durationNights: 4,
    heroImage: img("https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=1200&q=80", "Thailand beach"),
    gallery: [
      img("https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80", "Thailand temple"),
    ],
    overview: "Five days in Thailand — Bangkok's Grand Palace and floating markets, Pattaya's beaches, Coral Island snorkelling, and Thai cooking classes.",
    highlights: ["Grand Palace and Emerald Buddha", "Damnoen Saduak floating market", "Coral Island snorkelling", "Pattaya Walking Street", "Thai cooking class", "Alcazar cabaret show"],
    itinerary: [
      { day: 1, city: "Bangkok", title: "Arrival in Bangkok", description: "Arrive at BKK. Transfer to hotel.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Khao San Road"] },
      { day: 2, city: "Bangkok", title: "Bangkok Temples & Palace", description: "Grand Palace. Emerald Buddha. Wat Arun. Chao Phraya river cruise.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car + boat", activities: ["Grand Palace", "Wat Arun", "Chao Phraya cruise"] },
      { day: 3, city: "Bangkok → Pattaya", title: "Floating Market & Transfer", description: "Floating market. Transfer to Pattaya. Alcazar show.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car + coach", activities: ["Floating market", "Alcazar cabaret show"] },
      { day: 4, city: "Pattaya", title: "Coral Island", description: "Speedboat to Coral Island. Snorkelling, parasailing.", images: [], meals: ["breakfast", "dinner"], transfers: "Speedboat", activities: ["Coral Island", "Snorkelling"] },
      { day: 5, city: "Pattaya → Bangkok", title: "Farewell Thailand", description: "Thai cooking class. Transfer to BKK. Departure.", images: [], meals: ["breakfast"], transfers: "Coach + airport", activities: ["Thai cooking class", "Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 5, durationNights: 4, pricePerAdultINR: 27999, pricePerChildINR: 20000, singleSupplementINR: 9000, originalPricePerAdultINR: 34999, inclusionsExtra: ["3-star hotel in Bangkok", "Pattaya beach resort", "Coral Island trip"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 5, durationNights: 4, pricePerAdultINR: 42999, pricePerChildINR: 30000, singleSupplementINR: 15000, originalPricePerAdultINR: 53999, inclusionsExtra: ["4-star hotel Bangkok", "5-star Pattaya resort", "Thai spa session"], isDefault: false },
    ],
    departures: makeDepartures(12, 4, 5),
    departureCities: ["Delhi", "Mumbai", "Chennai", "Kolkata"],
    startingPriceINR: 27999,
    originalPriceINR: 34999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: true,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["November", "December", "January", "February", "March", "April"],
    inclusions: ["Return flights from India", "4 nights 3-star hotel", "Daily breakfast", "Grand Palace and temples", "Floating market tour", "Coral Island speedboat", "Snorkelling", "Thai cooking class", "Alcazar show", "All transfers", "Thailand visa", "Travel insurance"],
    exclusions: ["Lunch and most dinners", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Nov-Apr", "Dress modestly for temples"],
    visaDetails: "Thailand visa processing included — 15-day visa on arrival.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 10 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Bangkok", name: "Hotel Royal Bangkok", category: 3, nights: 2, note: "Sukhumvit area" },
      { city: "Pattaya", name: "D Varee Jomtien Beach", category: 4, nights: 2, note: "Beachfront Pattaya" },
    ],
    faqs: [
      { question: "Is Thailand safe?", answer: "Yes, Thailand is generally safe. Use metered taxis." },
    ],
    ratingAverage: 4.3,
    ratingCount: 520,
    isFeatured: false,
    isTrending: true,
    isBestseller: true,
    status: "published",
    seo: { title: "Thailand Beach & Bangkok — 5 Days 4 Nights from 27999", description: "Thailand tour with Bangkok temples, floating market, Pattaya Coral Island." },
    viewCount: 13800,
    enquiryCount: 550,
    bookingCount: 420,
    deletedAt: null,
    isDemoData: true,
  },

  // 47. Jaisalmer & Jodhpur Desert Safari
  {
    title: "Jaisalmer & Jodhpur Desert Safari",
    slug: "jaisalmer-jodhpur-desert-safari",
    subtitle: "Thar Desert, golden fort, camel safari, and Rajasthani culture",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Jaisalmer", "Jodhpur"],
    scope: "domestic",
    tripTypes: ["culture", "adventure", "honeymoon"],
    collections: ["best-of-india", "adventure-tours"],
    durationDays: 4,
    durationNights: 3,
    heroImage: img("https://images.unsplash.com/photo-1457576801217-013b2e230231?w=1200&q=80", "Jaisalmer desert"),
    gallery: [
      img("https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?w=800&q=80", "Jaisalmer fort"),
    ],
    overview: "Four days in Rajasthan's desert heartland — the Golden Fort of Jaisalmer, sunset camel safari in the Thar Desert, and Mehrangarh Fort.",
    highlights: ["Jaisalmer Golden Fort", "Thar Desert sunset camel safari", "Desert camping with cultural evening", "Sam Sand Dunes", "Mehrangarh Fort Jodhpur"],
    itinerary: [
      { day: 1, city: "Jaisalmer", title: "Arrival in Jaisalmer", description: "Arrive at Jaisalmer. Golden Fort.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Golden Fort"] },
      { day: 2, city: "Jaisalmer", title: "Desert Safari", description: "Gadisar Lake. Camel safari to Sam Sand Dunes. Cultural evening.", images: [], meals: ["breakfast", "dinner"], transfers: "Jeep + camel", activities: ["Sam Sand Dunes", "Camel safari", "Cultural evening"] },
      { day: 3, city: "Jaisalmer → Jodhpur", title: "Transfer to Jodhpur", description: "Transfer to Jodhpur. Mehrangarh Fort. Jaswant Thada.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Mehrangarh Fort", "Jaswant Thada"] },
      { day: 4, city: "Jodhpur", title: "Jodhpur & Departure", description: "Umaid Bhawan. Transfer to airport.", images: [], meals: ["breakfast"], transfers: "Airport transfer", activities: ["Umaid Bhawan", "Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 4, durationNights: 3, pricePerAdultINR: 15999, pricePerChildINR: 11000, singleSupplementINR: 7000, originalPricePerAdultINR: 21999, inclusionsExtra: ["3-star hotel + desert camp", "Camel safari"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 4, durationNights: 3, pricePerAdultINR: 24999, pricePerChildINR: 17000, singleSupplementINR: 10000, originalPricePerAdultINR: 32999, inclusionsExtra: ["Heritage hotel + luxury camp", "Jeep safari", "Private transfers"], isDefault: false },
    ],
    departures: makeDepartures(15, 5, 5),
    departureCities: ["Jodhpur", "Jaipur", "Delhi"],
    startingPriceINR: 15999,
    originalPriceINR: 21999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: false,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["October", "November", "December", "January", "February", "March"],
    inclusions: ["3 nights accommodation", "Desert camp with cultural evening", "Camel safari in Thar Desert", "Jeep safari", "Mehrangarh Fort", "Jaisalmer Golden Fort", "Jaswant Thada", "All meals", "All transfers", "Travel insurance"],
    exclusions: ["Flights to/from Jaisalmer", "Lunch", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Oct-Mar", "Carry warm layers for desert nights"],
    visaDetails: "No visa required for domestic travel.",
    cancellationPolicy: [
      { window: "More than 7 days before departure", charge: "20% of total" },
      { window: "3–7 days before departure", charge: "50% of total" },
      { window: "Less than 3 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Jaisalmer", name: "Desert Gateway Hotel", category: 3, nights: 2, note: "Heritage hotel near fort" },
      { city: "Jodhpur", name: "Haveli Inn Heeralal", category: 4, nights: 1, note: "Heritage haveli" },
    ],
    faqs: [
      { question: "Is the desert safe?", answer: "Yes, very safe. Female guides available on request." },
    ],
    ratingAverage: 4.4,
    ratingCount: 230,
    isFeatured: false,
    isTrending: true,
    isBestseller: false,
    status: "published",
    seo: { title: "Jaisalmer & Jodhpur Desert Safari — 4 Days 3 Nights from 15999", description: "Rajasthan desert tour with Jaisalmer Golden Fort, Thar Desert camel safari, Jodhpur Mehrangarh Fort." },
    viewCount: 6800,
    enquiryCount: 280,
    bookingCount: 180,
    deletedAt: null,
    isDemoData: true,
  },

  // 48. Bhutan Kingdom of Happiness
  {
    title: "Bhutan Kingdom of Happiness",
    slug: "bhutan-kingdom-of-happiness",
    subtitle: "Tiger's Nest, Punakha Dzong, Paro, and Himalayan landscapes",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Paro", "Thimphu", "Punakha"],
    scope: "international",
    tripTypes: ["culture", "leisure", "honeymoon"],
    collections: ["trending-international", "best-of-india"],
    durationDays: 6,
    durationNights: 5,
    heroImage: img("https://images.unsplash.com/photo-1561363433-d909b43d4c7c?w=1200&q=80", "Bhutan Tiger Nest"),
    gallery: [
      img("https://images.unsplash.com/photo-1626618010321-ff192286ef8e?w=800&q=80", "Bhutan monastery"),
    ],
    overview: "Six days in the world's happiest country — hike to the iconic Tiger's Nest Monastery perched on a cliff.",
    highlights: ["Tiger's Nest Monastery", "Punakha Dzong", "Dochula Pass with 108 chortens", "Thimphu Buddha Dordenma Statue", "Traditional hot stone bath", "Archery match"],
    itinerary: [
      { day: 1, city: "Paro → Thimphu", title: "Arrival & Drive to Thimphu", description: "Arrive at Paro. Buddha Dordenma. Tashichho Dzong.", images: [], meals: ["dinner"], transfers: "Private car", activities: ["Buddha Dordenma"] },
      { day: 2, city: "Thimphu", title: "Thimphu Sightseeing", description: "Memorial Chorten. Archery match.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Private car", activities: ["Memorial Chorten", "Archery match"] },
      { day: 3, city: "Thimphu → Punakha", title: "Dochula Pass to Punakha", description: "Dochula Pass. Punakha Dzong. River rafting.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Dochula Pass", "Punakha Dzong", "River rafting"] },
      { day: 4, city: "Punakha → Paro", title: "Drive to Paro", description: "Rinpung Dzong. National Museum. Farm house dinner.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Private car", activities: ["Rinpung Dzong", "Farmhouse dinner"] },
      { day: 5, city: "Paro", title: "Tiger's Nest Hike", description: "Hike to Tiger's Nest Monastery. Hot stone bath.", images: [], meals: ["breakfast", "dinner"], transfers: "Trekking guide", activities: ["Tiger's Nest hike", "Hot stone bath"] },
      { day: 6, city: "Paro", title: "Farewell Bhutan", description: "Chele La Pass. Transfer to Paro airport.", images: [], meals: ["breakfast"], transfers: "Airport transfer", activities: ["Chele La Pass", "Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 6, durationNights: 5, pricePerAdultINR: 44999, pricePerChildINR: 32000, singleSupplementINR: 16000, originalPricePerAdultINR: 54999, inclusionsExtra: ["3-star hotel", "Private car", "Guide", "Permits"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 6, durationNights: 5, pricePerAdultINR: 64999, pricePerChildINR: 46000, singleSupplementINR: 24000, originalPricePerAdultINR: 79999, inclusionsExtra: ["4-star resort", "Upgrade flights", "Hot stone bath"], isDefault: false },
    ],
    departures: makeDepartures(8, 3, 10),
    departureCities: ["Bagdogra", "Kolkata"],
    startingPriceINR: 44999,
    originalPriceINR: 54999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: true,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["March", "April", "May", "September", "October", "November"],
    inclusions: ["Return flights from India", "5 nights 3-star hotel", "All meals", "Private car with driver", "English-speaking guide", "Tiger's Nest hike", "Punakha Dzong", "Dochula Pass", "Hot stone bath", "Bhutan visa processing", "Travel insurance"],
    exclusions: ["Personal expenses", "Tips"],
    importantInfo: ["Best time: Mar-May and Sep-Nov", "Tiger's Nest requires moderate fitness"],
    visaDetails: "Bhutan visa processing included.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["50% advance at booking", "Balance 15 days before departure"],
    termsAndConditions: ["Carry comfortable walking shoes", "No shorts inside dzongs"],
    hotels: [
      { city: "Thimphu", name: "Hotel Kisa", category: 3, nights: 2, note: "City centre" },
      { city: "Punakha", name: "Punakha Resort", category: 4, nights: 1, note: "Riverside" },
      { city: "Paro", name: "Hotel Olathang", category: 3, nights: 2, note: "Near Paro town" },
    ],
    faqs: [
      { question: "Is a visa required?", answer: "Indian nationals do not need a visa. Others get a permit." },
    ],
    ratingAverage: 4.8,
    ratingCount: 160,
    isFeatured: true,
    isTrending: true,
    isBestseller: false,
    status: "published",
    seo: { title: "Bhutan Kingdom of Happiness — 6 Days 5 Nights from 44999", description: "Bhutan tour with Tiger's Nest Monastery, Punakha Dzong, Thimphu Buddha Dordenma." },
    viewCount: 6100,
    enquiryCount: 230,
    bookingCount: 140,
    deletedAt: null,
    isDemoData: true,
  },

  // 49. Singapore & Sentosa Island
  {
    title: "Singapore & Sentosa Island",
    slug: "singapore-sentosa-island",
    subtitle: "Marina Bay, Gardens by the Bay, Universal Studios, and Sentosa fun",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Singapore"],
    scope: "international",
    tripTypes: ["family", "leisure", "honeymoon"],
    collections: ["trending-international", "affordable-getaways"],
    durationDays: 4,
    durationNights: 3,
    heroImage: img("https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&q=80", "Singapore Marina Bay"),
    gallery: [
      img("https://images.unsplash.com/photo-1508964942454-1a56651d54ac?w=800&q=80", "Gardens by the Bay"),
    ],
    overview: "Four days in the Lion City — Marina Bay Sands, Gardens by the Bay's supertrees, Universal Studios on Sentosa Island.",
    highlights: ["Marina Bay Sands SkyPark", "Gardens by the Bay", "Universal Studios Singapore", "Night Safari", "Singapore River cruise", "Hawker centre food tour"],
    itinerary: [
      { day: 1, city: "Singapore", title: "Arrival & Marina Bay", description: "Arrive at Changi. Marina Bay Sands. Merlion Park. Light show.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Marina Bay Sands", "Merlion Park"] },
      { day: 2, city: "Singapore", title: "Gardens by the Bay & Sentosa", description: "Gardens by the Bay. Sentosa Island. Universal Studios.", images: [], meals: ["breakfast", "dinner"], transfers: "MRT + cable car", activities: ["Gardens by the Bay", "Universal Studios", "Sentosa"] },
      { day: 3, city: "Singapore", title: "City Tour & Night Safari", description: "Little India, Chinatown. Orchard Road. Night Safari.", images: [], meals: ["breakfast", "dinner"], transfers: "MRT + bus", activities: ["Little India", "Chinatown", "Night Safari"] },
      { day: 4, city: "Singapore", title: "Farewell Singapore", description: "Hawker centre food tour. River cruise. Transfer to Changi.", images: [], meals: ["breakfast"], transfers: "Airport transfer", activities: ["Hawker food tour", "Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 4, durationDays: 4, durationNights: 3, pricePerAdultINR: 45999, pricePerChildINR: 33000, singleSupplementINR: 15000, originalPricePerAdultINR: 57999, inclusionsExtra: ["4-star hotel", "Universal Studios ticket", "Gardens by the Bay", "Night Safari"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 5, durationDays: 4, durationNights: 3, pricePerAdultINR: 72999, pricePerChildINR: 52000, singleSupplementINR: 28000, originalPricePerAdultINR: 89999, inclusionsExtra: ["Marina Bay Sands hotel", "VIP Universal Studios", "S.E.A. Aquarium"], isDefault: false },
    ],
    departures: makeDepartures(10, 4, 5),
    departureCities: ["Delhi", "Mumbai", "Chennai", "Kolkata"],
    startingPriceINR: 45999,
    originalPriceINR: 57999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: false,
    activitiesIncluded: true,
    visaIncluded: true,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    inclusions: ["Return flights from India", "3 nights 4-star hotel", "Universal Studios ticket", "Gardens by the Bay", "Night Safari", "Marina Bay Sands SkyPark", "City tour", "Singapore visa", "All transfers", "Travel insurance"],
    exclusions: ["Lunch and dinner", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Year-round", "Hawker centres are the best value"],
    visaDetails: "Singapore visa processing included.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 10 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Singapore", name: "Hotel Boss", category: 4, nights: 3, note: "Tiong Bahru" },
    ],
    faqs: [
      { question: "Is Singapore expensive?", answer: "Hawker centres offer affordable meals from SGD 3-6." },
    ],
    ratingAverage: 4.5,
    ratingCount: 420,
    isFeatured: true,
    isTrending: true,
    isBestseller: true,
    status: "published",
    seo: { title: "Singapore & Sentosa Island — 4 Days 3 Nights from 45999", description: "Singapore tour with Marina Bay Sands, Gardens by the Bay, Universal Studios, Night Safari." },
    viewCount: 9500,
    enquiryCount: 400,
    bookingCount: 290,
    deletedAt: null,
    isDemoData: true,
  },

  // 50. Himachal Pradesh Hill Tour
  {
    title: "Himachal Pradesh Hill Tour",
    slug: "himachal-pradesh-hill-tour",
    subtitle: "Shimla, Manali, Dharamshala, and Dalhousie",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Shimla", "Manali", "Dharamshala", "Dalhousie"],
    scope: "domestic",
    tripTypes: ["honeymoon", "family", "leisure", "adventure"],
    collections: ["honeymoon-escapes", "best-of-india", "weekend-breaks"],
    durationDays: 8,
    durationNights: 7,
    heroImage: img("https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80", "Himachal mountains"),
    gallery: [
      img("https://images.unsplash.com/photo-1595665593673-bf1ad72905c0?w=800&q=80", "Manali mountains"),
    ],
    overview: "Eight days across Himachal Pradesh — Shimla's colonial charm, Manali's adventure sports, Dharamshala's Tibetan culture, and Dalhousie's Victorian-era architecture.",
    highlights: ["Shimla Mall Road and Christ Church", "Manali Solang Valley adventure sports", "Rohtang Pass or Atal Tunnel", "Dharamshala Tibetan monastery", "Dalhousie Khajjiar — Mini Switzerland of India", "Toy train from Kalka to Shimla"],
    itinerary: [
      { day: 1, city: "Chandigarh → Shimla", title: "Drive to Shimla", description: "Arrive at Chandigarh. Drive to Shimla (3 hrs). Mall Road evening walk.", images: [], meals: ["dinner"], transfers: "Private car", activities: ["Mall Road", "Christ Church"] },
      { day: 2, city: "Shimla", title: "Shimla Full Day", description: "Kufri day trip. Jakhu Temple. Toy train ride.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car + toy train", activities: ["Kufri", "Jakhu Temple", "Toy train"] },
      { day: 3, city: "Shimla → Manali", title: "Drive to Manali", description: "Scenic drive to Manali (8 hrs) via Kullu Valley.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Kullu Valley", "Manali Mall Road"] },
      { day: 4, city: "Manali", title: "Manali Local", description: "Hadimba Temple. Vashisht hot springs. Tibetan Monastery.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Hadimba Temple", "Vashisht hot springs"] },
      { day: 5, city: "Solang Valley", title: "Solang Valley Adventure", description: "Full day at Solang Valley. Paragliding, zorbing, cable car.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Paragliding", "Zorbing", "Cable car"] },
      { day: 6, city: "Manali → Dharamshala", title: "Drive to Dharamshala", description: "Drive to Dharamshala (9 hrs). McLeod Ganj walk.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["McLeod Ganj", "Tibetan market"] },
      { day: 7, city: "Dharamshala → Dalhousie", title: "Drive to Dalhousie", description: "Drive to Dalhousie (3.5 hrs). Khajjiar — Mini Switzerland.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Khajjiar", "Kalatop Wildlife Sanctuary"] },
      { day: 8, city: "Dalhousie → Chandigarh", title: "Return to Chandigarh", description: "Drive to Chandigarh (4 hrs). Transfer to airport.", images: [], meals: ["breakfast"], transfers: "Private car + airport", activities: ["Departure"] },
    ],
    variants: [
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 8, durationNights: 7, pricePerAdultINR: 30999, pricePerChildINR: 22000, singleSupplementINR: 12000, originalPricePerAdultINR: 40999, inclusionsExtra: ["3-star hotels", "Volvo transfer", "Solang Valley activities"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 8, durationNights: 7, pricePerAdultINR: 46999, pricePerChildINR: 33000, singleSupplementINR: 18000, originalPricePerAdultINR: 61999, inclusionsExtra: ["4-star hotels", "Private car", "Rohtang Pass permit"], isDefault: false },
    ],
    departures: makeDepartures(10, 4, 10),
    departureCities: ["Delhi", "Chandigarh"],
    startingPriceINR: 30999,
    originalPriceINR: 40999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: false,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["March", "April", "May", "October", "November", "December"],
    inclusions: ["7 nights accommodation", "All meals", "Private car with driver", "Solang Valley entry", "Hadimba Temple", "Kufri", "Dalhousie and Khajjiar", "McLeod Ganj sightseeing", "Travel insurance"],
    exclusions: ["Flights to/from Chandigarh", "Rohtang Pass permit", "Personal expenses", "Tips"],
    importantInfo: ["Best time: Mar-May and Oct-Dec", "Rohtang Pass open May-Oct", "Carry warm clothing"],
    visaDetails: "No visa required for domestic travel.",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 7 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing"],
    hotels: [
      { city: "Shimla", name: "Hotel Combermere", category: 3, nights: 2, note: "Near Mall Road" },
      { city: "Manali", name: "Apple Country Resort", category: 4, nights: 2, note: "Manali" },
      { city: "Dharamshala", name: "Hotel Tibet", category: 3, nights: 1, note: "McLeod Ganj" },
      { city: "Dalhousie", name: "Grand View Hotel", category: 4, nights: 2, note: "Dalhousie" },
    ],
    faqs: [
      { question: "Is Rohtang Pass included?", answer: "Rohtang Pass is seasonal and requires a separate permit. We assist." },
    ],
    ratingAverage: 4.5,
    ratingCount: 350,
    isFeatured: false,
    isTrending: true,
    isBestseller: false,
    status: "published",
    seo: { title: "Himachal Pradesh Hill Tour — 8 Days 7 Nights from 30999", description: "Himachal Pradesh tour with Shimla, Manali Solang Valley, Dharamshala and Dalhousie Khajjiar." },
    viewCount: 8700,
    enquiryCount: 370,
    bookingCount: 250,
    deletedAt: null,
    isDemoData: true,
  },
];

export { extraPackages };