"use server";

import "server-only";
import { connectDB } from "@/lib/db";
import { Package, Destination, Category, type IPackage, type IDestination, type ICategory } from "@/models";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 60);

const img = (url: string, alt: string) => ({
  url,
  alt,
  publicId: "",
  width: 1200,
  height: 800,
  type: "image" as const,
});

const today = new Date();

function makeDepartures(startOffsetDays: number, count: number, gapDays = 14) {
  const deps: IPackage["departures"] = [];
  for (let i = 0; i < count; i++) {
    const date = new Date(today);
    date.setDate(date.getDate() + startOffsetDays + i * gapDays);
    const seatsTotal = 20;
    const seatsBooked = Math.floor(Math.random() * 14);
    deps.push({
      _id: "" as never,
      date,
      returnDate: new Date(date.getTime() + (i % 2 === 0 ? 7 : 5) * 86400000),
      departureCity: "Delhi",
      seatsTotal,
      seatsBooked,
      priceAdjustmentINR: i === 0 ? -2000 : 0,
      isFixedDeparture: true,
      isGuaranteed: i === 0,
      status: seatsBooked >= seatsTotal ? "sold_out" : seatsBooked >= seatsTotal - 3 ? "filling_fast" : "open",
    });
  }
  return deps;
}

// ---------------------------------------------------------------------------
// Destinations
// ---------------------------------------------------------------------------

const destinations: Omit<IDestination, "_id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Bali",
    slug: "bali",
    aliases: ["Bali Island"],
    country: "Indonesia",
    countryCode: "ID",
    region: "Southeast Asia",
    type: "city",
    scope: "international",
    themes: ["beach", "honeymoon", "adventure", "wellness"],
    summary: "Tropical paradise with ancient temples, emerald rice terraces, and world-class surf.",
    description: "Bali is Indonesia's most famous island — a heady mix of spiritual retreats, volcanic landscapes, surf beaches, and a vibrant creative scene. From the terraced rice paddies of Ubud to the cliffside temples of Uluwatu, every corner tells a story.",
    heroImage: img("https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80", "Bali rice terraces at sunrise"),
    gallery: [
      img("https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80", "Bali temple"),
      img("https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80", "Bali beach"),
    ],
    startingPriceINR: 35000,
    recommendedDurationDays: 6,
    bestMonths: ["April", "May", "June", "July", "August", "September"],
    currencyUsed: "IDR",
    languages: ["Indonesian", "Balinese", "English"],
    timezone: "WITA (UTC+8)",
    visaNote: "Visa on arrival available for Indian passport holders",
    coordinates: { lat: -8.4095, lng: 115.0926 },
    highlights: ["Ubud Rice Terraces", "Uluwatu Temple", "Tanah Lot Sunset", "Nusa Penida", "Seminyak Beach"],
    faqs: [
      { question: "Do I need a visa for Bali?", answer: "Indian passport holders get a 30-day visa on arrival." },
    ],
    isFeatured: true,
    isTrending: true,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 1,
    status: "published",
    seo: { title: "Bali Tour Packages from India", description: "Book Bali holiday packages from Delhi, Mumbai. Flights + hotels included.", keywords: ["bali", "indonesia"] },
    viewCount: 12400,
    deletedAt: null,
  },
  {
    name: "Dubai",
    slug: "dubai",
    aliases: ["DXB"],
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East",
    type: "city",
    scope: "international",
    themes: ["luxury", "family", "shopping", "adventure"],
    summary: "Futuristic skyline, desert adventures, and luxury living in one glittering city.",
    description: "Dubai defies imagination. From the world's tallest building to vast desert dunes, from luxury shopping malls to traditional souks — this city has redefined what a destination can be.",
    heroImage: img("https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80", "Dubai skyline at night"),
    gallery: [
      img("https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&q=80", "Dubai desert safari"),
      img("https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80", "Burj Khalifa"),
    ],
    startingPriceINR: 42000,
    recommendedDurationDays: 5,
    bestMonths: ["October", "November", "December", "January", "February", "March"],
    currencyUsed: "AED",
    languages: ["Arabic", "English", "Hindi", "Urdu"],
    timezone: "GST (UTC+4)",
    visaNote: "E-visa available for Indian passport holders",
    coordinates: { lat: 25.2048, lng: 55.2708 },
    highlights: ["Burj Khalifa", "Desert Safari", "Dubai Mall", "Palm Jumeirah", "Dhow Cruise"],
    faqs: [
      { question: "Is Dubai expensive?", answer: "Options exist for every budget. Budget packages from ₹42,000 per person." },
    ],
    isFeatured: true,
    isTrending: true,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 2,
    status: "published",
    seo: { title: "Dubai Tour Packages from India", description: "Affordable Dubai packages with flights from major Indian cities.", keywords: ["dubai", "uae"] },
    viewCount: 15800,
    deletedAt: null,
  },
  {
    name: "Himachal Pradesh",
    slug: "himachal-pradesh",
    aliases: ["Himachal", "HP"],
    country: "India",
    countryCode: "IN",
    region: "North India",
    type: "region",
    scope: "domestic",
    themes: ["mountain", "adventure", "honeymoon", "family"],
    summary: "Snow-capped peaks, apple orchards, and colonial hill stations in the heart of the Himalayas.",
    description: "Himachal Pradesh offers the quintessential Indian mountain experience. From Shimla's colonial charm to Dharamshala's spiritual vibe and Manali's adventure thrills.",
    heroImage: img("https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80", "Himachal mountains"),
    gallery: [
      img("https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&q=80", "Manali valley"),
      img("https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800&q=80", "Shimla toy train"),
    ],
    startingPriceINR: 15000,
    recommendedDurationDays: 7,
    bestMonths: ["March", "April", "May", "June", "October", "November", "December"],
    languages: ["Hindi", "Pahari", "English"],
    timezone: "IST (UTC+5:30)",
    visaNote: "No visa required for domestic travel",
    coordinates: { lat: 31.6, lng: 77.3 },
    highlights: ["Rohtang Pass", "Hadimba Temple", "Solang Valley", "McLeod Ganj", "Spiti Valley"],
    faqs: [
      { question: "Do I need a passport for Himachal?", answer: "No, it's domestic. A government-issued photo ID is sufficient." },
    ],
    isFeatured: true,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 3,
    status: "published",
    seo: { title: "Himachal Pradesh Tour Packages", description: "Manali, Shimla, Dharamshala packages with hotel and transfers." },
    viewCount: 9800,
    deletedAt: null,
  },
  {
    name: "Kerala",
    slug: "kerala",
    aliases: ["God's Own Country"],
    country: "India",
    countryCode: "IN",
    region: "South India",
    type: "region",
    scope: "domestic",
    themes: ["beach", "wellness", "honeymoon", "nature"],
    summary: "Backwaters, hill stations, and Ayurveda — God's own country lives up to the name.",
    description: "Kerala offers a gentle, verdant escape. Cruise the backwaters of Alleppey, trek the Western Ghats, rejuvenate with Ayurveda, and unwind on the pristine beaches of Kovalam.",
    heroImage: img("https://images.unsplash.com/photo-1593693397690-362cb9666c2f?w=1200&q=80", "Kerala backwaters houseboat"),
    gallery: [
      img("https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80", "Munnar tea gardens"),
      img("https://images.unsplash.com/photo-1580137187710-1c31e9e2dd17?w=800&q=80", "Kovalam beach"),
    ],
    startingPriceINR: 18000,
    recommendedDurationDays: 6,
    bestMonths: ["September", "October", "November", "December", "January", "February"],
    languages: ["Malayalam", "English", "Tamil", "Hindi"],
    timezone: "IST (UTC+5:30)",
    visaNote: "No visa required for domestic travel",
    coordinates: { lat: 10.5, lng: 76.5 },
    highlights: ["Alleppey Houseboat", "Munnar Tea Gardens", "Thekkady Wildlife", "Kovalam Beach", "Ayurveda Spa"],
    faqs: [
      { question: "What is the best time for a backwater cruise?", answer: "October to March offers the best weather for houseboat cruises." },
    ],
    isFeatured: true,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: true,
    displayOrder: 4,
    status: "published",
    seo: { title: "Kerala Holiday Packages", description: "Munnar, Alleppey, Kovalam packages with houseboat stays." },
    viewCount: 11200,
    deletedAt: null,
  },
  {
    name: "Leh Ladakh",
    slug: "leh-ladakh",
    aliases: ["Ladakh", "Leh"],
    country: "India",
    countryCode: "IN",
    region: "North India",
    type: "region",
    scope: "domestic",
    themes: ["adventure", "mountain", "road-trip", "trekking"],
    summary: "The rooftop of India — barren beauty, crystal lakes, and ancient monasteries.",
    description: "Leh Ladakh is a high-altitude desert that looks like another planet. Dramatic landscapes of Nubra Valley, surreal colours of Pangong Lake, and the spiritual calm of Thiksey Monastery.",
    heroImage: img("https://images.unsplash.com/photo-1583998998990-82ab066cf252?w=1200&q=80", "Pangong Lake Ladakh"),
    gallery: [
      img("https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80", "Ladakh mountains"),
      img("https://images.unsplash.com/photo-1604391652849-3e77942344c9?w=800&q=80", "Nubra Valley camel"),
    ],
    startingPriceINR: 25000,
    recommendedDurationDays: 8,
    bestMonths: ["May", "June", "July", "August", "September"],
    languages: ["Ladakhi", "Hindi", "English"],
    timezone: "IST (UTC+5:30)",
    visaNote: "No visa required for domestic travel. Inner Line Permit needed for border areas.",
    coordinates: { lat: 34.3, lng: 77.2 },
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La", "Thiksey Monastery", "Magnetic Hill"],
    faqs: [
      { question: "Is Leh safe for travellers?", answer: "Yes, Ladakh is very safe. The local people are extremely hospitable." },
    ],
    isFeatured: true,
    isTrending: true,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 5,
    status: "published",
    seo: { title: "Leh Ladakh Tour Packages", description: "Leh Ladakh bike tour and family packages from Delhi." },
    viewCount: 13500,
    deletedAt: null,
  },
  {
    name: "Sri Lanka",
    slug: "sri-lanka",
    aliases: ["Ceylon", "LKA"],
    country: "Sri Lanka",
    countryCode: "LK",
    region: "South Asia",
    type: "country",
    scope: "international",
    themes: ["beach", "wildlife", "culture", "train-journey"],
    summary: "Ancient ruins, wildlife safaris, world-famous tea, and golden beaches in a compact island.",
    description: "Sri Lanka packs extraordinary variety into a small island. Ride the scenic train to Ella, climb Sigiriya, walk ancient temples in Kandy.",
    heroImage: img("https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?w=1200&q=80", "Sigiriya Rock Fortress"),
    gallery: [
      img("https://images.unsplash.com/photo-1544207240-8c9b3a3e3f5c?w=800&q=80", "Sri Lankan train"),
      img("https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80", "Ella Nine Arch Bridge"),
    ],
    startingPriceINR: 28000,
    recommendedDurationDays: 6,
    bestMonths: ["December", "January", "February", "March"],
    currencyUsed: "LKR",
    languages: ["Sinhala", "Tamil", "English"],
    timezone: "SLST (UTC+5:30)",
    visaNote: "E-visa available for Indian passport holders",
    coordinates: { lat: 7.9, lng: 80.7 },
    highlights: ["Sigiriya Rock", "Ella Train Ride", "Kandy Temple", "Mirissa Beach", "Yala Safari"],
    faqs: [
      { question: "How do I get an ETA for Sri Lanka?", answer: "Apply online at eta.gov.lk — approved within 24-72 hours." },
    ],
    isFeatured: true,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 6,
    status: "published",
    seo: { title: "Sri Lanka Tour Packages", description: "Affordable Sri Lanka packages with ETA assistance." },
    viewCount: 8900,
    deletedAt: null,
  },
  {
    name: "Goa",
    slug: "goa",
    aliases: ["Goa State"],
    country: "India",
    countryCode: "IN",
    region: "West India",
    type: "region",
    scope: "domestic",
    themes: ["beach", "nightlife", "family", "honeymoon"],
    summary: "Sun, sand, and spice — Goa is India's favourite beach escape.",
    description: "Goa is more than beaches. Explore Portuguese heritage in Old Goa, trek the Western Ghats, cruise the Mandovi River, and feast on the best seafood on the west coast.",
    heroImage: img("https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80", "Goa palm beach"),
    gallery: [
      img("https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", "Goa Palolem beach"),
      img("https://images.unsplash.com/photo-1593368607364-2bcde5e2ffa6?w=800&q=80", "Goa Portuguese church"),
    ],
    startingPriceINR: 10000,
    recommendedDurationDays: 4,
    bestMonths: ["November", "December", "January", "February"],
    languages: ["Konkani", "Marathi", "Hindi", "English", "Portuguese"],
    timezone: "IST (UTC+5:30)",
    visaNote: "No visa required for domestic travel",
    coordinates: { lat: 15.3, lng: 74.1 },
    highlights: ["Baga Beach", "Dudhsagar Falls", "Old Goa Churches", "Anjuna Market", "Fort Aguada"],
    faqs: [
      { question: "What is the best time to visit Goa?", answer: "November to February offers the best weather — cool and dry." },
    ],
    isFeatured: true,
    isTrending: false,
    hotelFeatured: true,
    packageFeatured: true,
    displayOrder: 7,
    status: "published",
    seo: { title: "Goa Holiday Packages", description: "Goa beach packages with flights and hotels from Delhi, Mumbai." },
    viewCount: 22100,
    deletedAt: null,
  },
  {
    name: "Jaipur",
    slug: "jaipur",
    aliases: ["Pink City"],
    country: "India",
    countryCode: "IN",
    region: "North India",
    type: "city",
    scope: "domestic",
    themes: ["heritage", "culture", "family", "honeymoon"],
    summary: "The Pink City — palaces, forts, and Rajasthani grandeur at every turn.",
    description: "Jaipur, the capital of Rajasthan, is a city of colour and grandeur. From the amber walls of Amber Fort to the intricate Hawa Mahal, every street is a piece of living history.",
    heroImage: img("https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200&q=80", "Amber Fort Jaipur"),
    gallery: [
      img("https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800&q=80", "Hawa Mahal"),
      img("https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80", "Jaipur city palace"),
    ],
    startingPriceINR: 12000,
    recommendedDurationDays: 4,
    bestMonths: ["October", "November", "December", "January", "February", "March"],
    languages: ["Hindi", "Rajasthani", "English"],
    timezone: "IST (UTC+5:30)",
    visaNote: "No visa required for domestic travel",
    coordinates: { lat: 26.9, lng: 75.8 },
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Chokhi Dhani"],
    faqs: [
      { question: "How many days are ideal for Jaipur?", answer: "3-4 days covers all major attractions comfortably." },
    ],
    isFeatured: true,
    isTrending: false,
    hotelFeatured: false,
    packageFeatured: true,
    displayOrder: 8,
    status: "published",
    seo: { title: "Jaipur Tour Packages", description: "Jaipur, Jodhpur, Udaipur Rajasthan tour packages." },
    viewCount: 10400,
    deletedAt: null,
  },
];

// ---------------------------------------------------------------------------
// Demo packages
// ---------------------------------------------------------------------------

const packages = [
  // 1. Bali Bliss
  {
    title: "Bali Bliss",
    slug: "bali-bliss",
    subtitle: "Beaches, temples & rice terraces — the complete Bali experience",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Denpasar", "Ubud", "Uluwatu", "Nusa Dua", "Seminyak"],
    scope: "international",
    tripTypes: ["honeymoon", "leisure"],
    collections: ["trending-international", "honeymoon-escapes"],
    durationDays: 6,
    durationNights: 5,
    heroImage: img("https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80", "Bali rice terraces at sunrise"),
    gallery: [
      img("https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80", "Bali temple"),
      img("https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80", "Bali beach"),
    ],
    overview: "Six days in Bali that balance relaxation with discovery. Morning yoga in Ubud, sunset at Tanah Lot, a sunrise trek up Mount Batur, and three nights on the beach in Nusa Dua. Flights, four-star stays, all transfers, and a private driver included.",
    highlights: ["Sunrise Mount Batur trek with hot springs", "Ubud rice terrace walk and cooking class", "Tanah Lot temple at sunset", "Nusa Penida day trip with Kelingking Beach", "Private candlelit dinner on Seminyak beach", "Traditional Balinese spa treatment"],
    itinerary: [
      { day: 1, city: "Denpasar → Nusa Dua", title: "Arrival & Beach Welcome", description: "Touch down at Ngurah Rai International Airport, meet your private driver, and transfer to your Nusa Dua resort. Evening at leisure.", images: [], meals: ["dinner"], hotel: "Nusa Dua Beach Hotel & Spa 4★", transfers: "Private airport transfer", activities: ["Beach walk", "Welcome dinner"] },
      { day: 2, city: "Nusa Dua", title: "Beach Day & Water Sports", description: "Free morning to relax. Afternoon optional water sports — parasailing, jet ski, snorkelling. Evening Balinese massage at the resort spa.", images: [], meals: ["breakfast"], hotel: "Nusa Dua Beach Hotel & Spa 4★", transfers: "", activities: ["Beach relaxation", "Optional water sports", "Balinese massage"], optionalExperiences: ["Snorkelling at Blue Point", "Sunset dolphin cruise"] },
      { day: 3, city: "Ubud", title: "Cultural Heart of Bali", description: "Drive to Ubud through spice plantations. Visit the Sacred Monkey Forest, explore the Ubud Art Market, and attend a traditional Balinese cooking class.", images: [], meals: ["breakfast", "lunch"], hotel: "Ubud Hanging Gardens 5★", transfers: "Private car, 90 mins", activities: ["Monkey Forest", "Art Market", "Cooking class"] },
      { day: 4, city: "Ubud → Kintamani", title: "Mount Batur Sunrise Trek", description: "Wake at 2:30 AM for the Mount Batur sunrise trek. Trek 2 hours to the summit for sunrise over Lake Batur, then descend for a hot spring soak.", images: [], meals: ["breakfast", "lunch"], hotel: "Ubud Hanging Gardens 5★", transfers: "Private transfer", activities: ["Mount Batur trek", "Hot springs", "Tegalalang Rice Terrace visit"] },
      { day: 5, city: "Uluwatu → Seminyak", title: "Temples & Southern Beaches", description: "Visit Tanah Lot temple for sunset, then Uluwatu Temple perched on a cliff. Evening kecak fire dance. Dinner in Seminyak.", images: [], meals: ["breakfast", "dinner"], hotel: "The Haven Seminyak 4★", transfers: "Private car", activities: ["Tanah Lot sunset", "Uluwatu Temple", "Kecak dance"] },
      { day: 6, city: "Seminyak → Airport", title: "Farewell Bali", description: "Leisurely morning with breakfast at a beachfront cafe. Last-minute shopping, then transfer to the airport.", images: [], meals: ["breakfast"], transfers: "Private airport transfer", activities: ["Breakfast at beachfront cafe", "Shopping"] },
    ],
    variants: [
      { key: "3-star", label: "Comfort", hotelCategory: 3, durationDays: 6, durationNights: 5, pricePerAdultINR: 34999, pricePerChildINR: 25000, singleSupplementINR: 15000, originalPricePerAdultINR: 41999, inclusionsExtra: ["Pool access", "Daily breakfast"], isDefault: false },
      { key: "4-star", label: "Premium", hotelCategory: 4, durationDays: 6, durationNights: 5, pricePerAdultINR: 54999, pricePerChildINR: 35000, singleSupplementINR: 22000, originalPricePerAdultINR: 65999, inclusionsExtra: ["Spa credit 2000", "Private driver", "Candlelight dinner"], isDefault: true },
      { key: "5-star", label: "Luxury", hotelCategory: 5, durationDays: 6, durationNights: 5, pricePerAdultINR: 89999, pricePerChildINR: 55000, singleSupplementINR: 45000, originalPricePerAdultINR: 107999, inclusionsExtra: ["All meals", "Private villa", "Helicopter tour"], isDefault: false },
    ],
    departures: makeDepartures(7, 6),
    departureCities: ["Delhi", "Mumbai", "Bangalore"],
    startingPriceINR: 34999,
    originalPriceINR: 41999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: true,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["April", "May", "June", "July", "August", "September"],
    inclusions: ["Return flights from Delhi/Mumbai/Bangalore", "5 nights accommodation (breakfast included)", "All inter-hotel transfers by private AC car", "Mount Batur sunrise trek with guide", "Kecak fire dance entry ticket", "Balinese spa treatment", "Cooking class with market tour", "Travel insurance"],
    exclusions: ["Lunch and dinner (unless specified)", "Personal expenses and tips", "Water sports activities", "Nusa Penida fast boat ticket", "Items of personal nature"],
    importantInfo: ["Passport must be valid for 6 months from date of travel", "Visa on arrival fee of 3500 approx payable at Bali airport", "Carry Indian Rupees or USD for local expenses"],
    visaDetails: "Indian passport holders are eligible for Visa on Arrival in Indonesia — 30 days, extendable once.",
    cancellationPolicy: [
      { window: "More than 30 days before departure", charge: "10% of total" },
      { window: "15–30 days before departure", charge: "50% of total" },
      { window: "Less than 15 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking to confirm", "Balance due 15 days before departure"],
    termsAndConditions: ["Prices are per person on twin sharing basis", "Prices are subject to change with currency fluctuation", "Airline and hotel names are indicative and may change"],
    hotels: [
      { city: "Nusa Dua", name: "Nusa Dua Beach Hotel & Spa", category: 4, nights: 2, note: "Beachfront, pool access" },
      { city: "Ubud", name: "Ubud Hanging Gardens", category: 5, nights: 2, note: "Pool villas with valley view" },
      { city: "Seminyak", name: "The Haven Seminyak", category: 4, nights: 1, note: "Steps from Seminyak Beach" },
    ],
    faqs: [
      { question: "Is Bali safe for solo female travellers?", answer: "Yes, Bali is one of the safest destinations for solo travellers, especially in tourist areas." },
      { question: "What is included in the flights?", answer: "Return economy class flights from your chosen departure city with a 20 kg check-in allowance." },
    ],
    ratingAverage: 4.7,
    ratingCount: 234,
    isFeatured: true,
    isTrending: true,
    isBestseller: true,
    status: "published",
    seo: { title: "Bali Bliss — 6 Days 5 Nights from 34999", description: "Bali package with flights, 4★ hotels, Mount Batur trek and Ubud cultural tour.", keywords: ["bali", "bali package", "bali honeymoon"] },
    viewCount: 5600,
    enquiryCount: 180,
    bookingCount: 95,
    deletedAt: null,
  },

  // 2. Dubai Dreams
  {
    title: "Dubai Dreams",
    slug: "dubai-dreams",
    subtitle: "Desert magic, sky-high views, and shopping galore",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Dubai", "Abu Dhabi", "Sharjah"],
    scope: "international",
    tripTypes: ["family", "leisure"],
    collections: ["trending-international", "flight-inclusive"],
    durationDays: 5,
    durationNights: 4,
    heroImage: img("https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80", "Dubai skyline"),
    gallery: [
      img("https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&q=80", "Dubai desert safari"),
      img("https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80", "Burj Khalifa"),
    ],
    overview: "Five days that capture the full spectacle of Dubai — from the record-breaking heights of Burj Khalifa to the golden silence of the desert. Includes a desert safari, dhow cruise, and a day trip to Abu Dhabi's Sheikh Zayed Grand Mosque.",
    highlights: ["Burj Khalifa 124th floor access", "Desert safari with BBQ dinner", "Sheikh Zayed Grand Mosque visit", "Dhow cruise with dinner", "Dubai Mall and Aquarium", "Global Village entry"],
    itinerary: [
      { day: 1, city: "Dubai", title: "Arrival & City Orientation", description: "Arrive at DXB, transfer to hotel. Evening free to explore the Marina Walk.", images: [], meals: [], transfers: "Private airport transfer", activities: ["Hotel check-in", "Marina Walk"], optionalExperiences: ["Dubai Frame visit"] },
      { day: 2, city: "Dubai", title: "Desert Safari", description: "Late afternoon pickup for desert safari — dune bashing, camel ride, sunset photography, followed by BBQ dinner with belly dance and tanoura shows.", images: [], meals: ["dinner"], transfers: "Safari pickup from hotel", activities: ["Dune bashing", "Camel ride", "BBQ dinner with shows"], optionalExperiences: ["Quad bike ride", "Sandboarding"] },
      { day: 3, city: "Dubai", title: "Burj Khalifa & Downtown", description: "Visit Burj Khalifa 124th and 125th floors. Explore the Dubai Mall. Evening at Downtown.", images: [], meals: ["breakfast"], transfers: "Private car", activities: ["Burj Khalifa", "Dubai Mall", "Fountain show"], optionalExperiences: ["At the Top SKY experience", "Dhow cruise dinner"] },
      { day: 4, city: "Abu Dhabi", title: "Sheikh Zayed Mosque & Louvre", description: "Day trip to Abu Dhabi. Visit the magnificent Sheikh Zayed Grand Mosque, then the Louvre Abu Dhabi.", images: [], meals: ["breakfast"], transfers: "Private car, 1.5 hrs each way", activities: ["Grand Mosque", "Louvre Abu Dhabi", "Corniche walk"] },
      { day: 5, city: "Dubai → Airport", title: "Global Village & Departure", description: "Morning at Global Village for shopping. Transfer to DXB for your flight home.", images: [], meals: ["breakfast"], transfers: "Private airport transfer", activities: ["Global Village"] },
    ],
    variants: [
      { key: "3-star", label: "Comfort", hotelCategory: 3, durationDays: 5, durationNights: 4, pricePerAdultINR: 42999, pricePerChildINR: 32000, singleSupplementINR: 18000, originalPricePerAdultINR: 52999, inclusionsExtra: ["Daily breakfast"], isDefault: false },
      { key: "4-star", label: "Premium", hotelCategory: 4, durationDays: 5, durationNights: 4, pricePerAdultINR: 64999, pricePerChildINR: 45000, singleSupplementINR: 28000, originalPricePerAdultINR: 77999, inclusionsExtra: ["Daily breakfast & dinner", "Desert safari BBQ", "Dhow cruise"], isDefault: true },
      { key: "5-star", label: "Luxury", hotelCategory: 5, durationDays: 5, durationNights: 4, pricePerAdultINR: 109999, pricePerChildINR: 70000, singleSupplementINR: 55000, originalPricePerAdultINR: 134999, inclusionsExtra: ["All meals", "Burj Khalifa VIP access", "Limousine transfers"], isDefault: false },
    ],
    departures: makeDepartures(14, 8, 10),
    departureCities: ["Delhi", "Mumbai", "Chennai", "Hyderabad"],
    startingPriceINR: 42999,
    originalPriceINR: 52999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: true,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["October", "November", "December", "January", "February", "March"],
    inclusions: ["Return flights from all major Indian cities", "4 nights hotel accommodation", "Daily breakfast; dinner on selected days", "All transfers and sightseeing by private AC vehicle", "Desert safari with BBQ dinner and live entertainment", "Burj Khalifa 124th & 125th floor tickets", "Sheikh Zayed Mosque and Louvre Abu Dhabi entry", "Dubai visa processing assistance", "Travel insurance"],
    exclusions: ["Lunch (except where mentioned)", "Personal expenses, tips, and shopping", "Any services not specifically mentioned", "Dubai visa fee", "Optional tours not included"],
    importantInfo: ["Visa processing takes 3-5 working days", "Carry passport copies at all times in Dubai", "Dress modestly when visiting mosques (provided)"],
    visaDetails: "UAE visa processing included. Indian passport holders get a 30-day tourist visa.",
    cancellationPolicy: [
      { window: "More than 30 days before departure", charge: "15% of total" },
      { window: "15–30 days before departure", charge: "50% of total" },
      { window: "Less than 15 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance due 10 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing basis", "Flight timings subject to change by airline", "Hotel check-in at 3 PM, check-out at 12 PM"],
    hotels: [{ city: "Dubai", name: "Ibis Deira Hotel", category: 3, nights: 4, note: "Near Deira City Centre" }],
    faqs: [
      { question: "Do I need travel insurance for Dubai?", answer: "Travel insurance is strongly recommended and is included in our packages." },
      { question: "What is the flight duration to Dubai?", answer: "Approximately 3.5 hours from most Indian metros." },
    ],
    ratingAverage: 4.5,
    ratingCount: 312,
    isFeatured: true,
    isTrending: true,
    isBestseller: true,
    status: "published",
    seo: { title: "Dubai Dreams — 5 Days 4 Nights from 42999", description: "Dubai holiday package with flights, Burj Khalifa, desert safari and Abu Dhabi tour." },
    viewCount: 8900,
    enquiryCount: 290,
    bookingCount: 165,
    deletedAt: null,
  },

  // 3. Himalayan Escape
  {
    title: "Himalayan Escape",
    slug: "himalayan-escape",
    subtitle: "Manali, Kasol & Solang Valley — mountains at their finest",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Manali", "Kasol", "Solang Valley", "Kullu", "Naggar"],
    scope: "domestic",
    tripTypes: ["adventure", "honeymoon", "family"],
    collections: ["best-of-india", "adventure-tours"],
    durationDays: 7,
    durationNights: 6,
    heroImage: img("https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80", "Manali mountains"),
    gallery: [
      img("https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&q=80", "Solang Valley"),
      img("https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800&q=80", "Manali Hadimba temple"),
    ],
    overview: "Seven days in Himachal Pradesh covering the best of Kullu Valley and Parvati Valley. River rafting in Kasol, paragliding in Solang, old temples, and bonfire evenings in a riverside cottage.",
    highlights: ["Solang Valley paragliding and zorbing", "Parvati River rafting", "Manikaran hot springs visit", "Naggar Castle and art gallery", "Riverfront bonfire dinner", "Himalayan adventure sports"],
    itinerary: [
      { day: 1, city: "Manali", title: "Arrival in Manali", description: "Drive from Delhi via Volvo or private cab. Check in to a riverside resort in Old Manali.", images: [], meals: ["dinner"], transfers: "Volvo / Private cab from Delhi", activities: ["Resort check-in", "Evening walk at Mall Road"] },
      { day: 2, city: "Solang Valley", title: "Adventure Day at Solang", description: "Full day at Solang Valley — paragliding, zorbing, ATV rides, and the ropeway. Return to resort for a bonfire dinner.", images: [], meals: ["breakfast", "dinner"], transfers: "15 min drive", activities: ["Paragliding", "Zorbing", "ATV ride", "Ropeway"], optionalExperiences: ["Snow activities (winter only)", "Camping in Solang"] },
      { day: 3, city: "Manali", title: "Local Manali Sightseeing", description: "Visit Hadimba Temple, Vashisht hot springs, and the Manu Temple. Explore Old Manali's cafes and handicraft shops.", images: [], meals: ["breakfast"], transfers: "Local cab", activities: ["Hadimba Temple", "Vashisht hot springs", "Cafe walk"] },
      { day: 4, city: "Kasol", title: "Parvati Valley — Kasol & Malana", description: "Drive to Kasol (1.5 hrs). Trek to Malana village, lunch by the Parvati River, and camp by the riverside.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Private car", activities: ["Malana trek", "Parvati River walk", "Riverside camp"] },
      { day: 5, city: "Manikaran → Kasol", title: "Hot Springs & Trekking", description: "Visit Manikaran hot springs and Gurudwara. Afternoon trek to Tosh village.", images: [], meals: ["breakfast", "lunch"], transfers: "Local transport", activities: ["Manikaran hot springs", "Tosh village trek"] },
      { day: 6, city: "Naggar", title: "Naggar Castle & Art", description: "Visit Naggar Castle, the Nicholas Roerich art gallery, and the ancient Shiva temples. Drive back through apple orchards.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Naggar Castle", "Roerich Gallery", "Apple orchard walk"] },
      { day: 7, city: "Manali → Delhi", title: "Farewell to the Hills", description: "Morning at leisure — last-minute shopping at the Mall Road. Drive or Volvo back to Delhi.", images: [], meals: ["breakfast"], transfers: "Volvo / Private cab to Delhi", activities: ["Mall Road shopping"] },
    ],
    variants: [
      { key: "budget", label: "Budget Stay", hotelCategory: 3, durationDays: 7, durationNights: 6, pricePerAdultINR: 14999, pricePerChildINR: 10000, singleSupplementINR: 8000, originalPricePerAdultINR: 18999, inclusionsExtra: ["Budget guesthouse", "Shared transfers"], isDefault: false },
      { key: "standard", label: "Standard", hotelCategory: 4, durationDays: 7, durationNights: 6, pricePerAdultINR: 22999, pricePerChildINR: 16000, singleSupplementINR: 12000, originalPricePerAdultINR: 27999, inclusionsExtra: ["3-star hotel", "Sightseeing by tempo traveller", "Bonfire dinner"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 7, durationNights: 6, pricePerAdultINR: 32999, pricePerChildINR: 22000, singleSupplementINR: 18000, originalPricePerAdultINR: 39999, inclusionsExtra: ["4-star resort", "Private cab", "All adventure activities included", "Riverfront cottage"], isDefault: false },
    ],
    departures: makeDepartures(10, 5, 14),
    departureCities: ["Delhi", "Chandigarh"],
    startingPriceINR: 14999,
    originalPriceINR: 18999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: false,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "group",
    instantConfirmation: true,
    recommendedSeason: ["March", "April", "May", "June", "October", "November", "December"],
    inclusions: ["6 nights accommodation (twin sharing)", "Daily breakfast; dinner on selected days", "All sightseeing and transfers by tempo traveller / private vehicle", "Paragliding and zorbing in Solang Valley", "River rafting in Kasol", "Bonfire dinner with music", "All applicable taxes"],
    exclusions: ["Flights / train to Manali", "Lunch and snacks", "Personal expenses", "Adventure activity insurance"],
    importantInfo: ["Carry warm clothing even in summer — evenings are cold", "Rohtang Pass may be closed during heavy snow", "Carry a first-aid kit for high-altitude areas"],
    visaDetails: "",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["50% advance at booking to block seats", "Balance due 5 days before departure"],
    termsAndConditions: ["Group size: 10 to 20 travellers", "Minimum 6 passengers required for departure", "Itinerary subject to weather conditions"],
    hotels: [{ city: "Manali", name: "Himalayan River Resort", category: 4, nights: 6, note: "Riverside cottages, Mall Road 2 km" }],
    faqs: [
      { question: "Is Rohtang Pass included?", answer: "Rohtang Pass is not guaranteed — it depends on permits and weather. We visit Solang Valley and Atal Tunnel as alternatives." },
    ],
    ratingAverage: 4.3,
    ratingCount: 156,
    isFeatured: true,
    isTrending: false,
    isBestseller: false,
    status: "published",
    seo: { title: "Himalayan Escape — Manali & Kasol 7 Days from 14999", description: "Himachal Pradesh group tour with adventure sports and bonfire." },
    viewCount: 4200,
    enquiryCount: 120,
    bookingCount: 65,
    deletedAt: null,
  },

  // 4. Kerala God's Own Country
  {
    title: "Kerala God's Own Country",
    slug: "kerala-gods-own-country",
    subtitle: "Backwaters, Ayurveda & misty hills — South India's finest",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Cochin", "Munnar", "Thekkady", "Alleppey", "Kovalam"],
    scope: "domestic",
    tripTypes: ["honeymoon", "wellness", "family"],
    collections: ["best-of-india", "honeymoon-escapes", "family-holidays"],
    durationDays: 6,
    durationNights: 5,
    heroImage: img("https://images.unsplash.com/photo-1593693397690-362cb9666c2f?w=1200&q=80", "Kerala backwaters houseboat"),
    gallery: [
      img("https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80", "Munnar tea gardens"),
      img("https://images.unsplash.com/photo-1580137187710-1c31e9e2dd17?w=800&q=80", "Kovalam beach"),
    ],
    overview: "The classic Kerala circuit: Cochin's heritage, Munnar's misty tea gardens, Thekkady's wildlife, Alleppey's iconic houseboat, and Kovalam's crescent beach. A wellness-first itinerary with included Ayurvedic massage.",
    highlights: ["Overnight houseboat cruise in Alleppey backwaters", "Kathakali dance performance in Cochin", "Tea plantation walk in Munnar", "Periyar Wildlife Sanctuary", "Ayurvedic full-body massage", "Kovalam beach sunset"],
    itinerary: [
      { day: 1, city: "Cochin", title: "Arrival in Cochin", description: "Arrive at Cochin International Airport. Visit Fort Kochi, St. Francis Church, and the Chinese fishing nets. Evening Kathakali performance.", images: [], meals: ["dinner"], transfers: "Private cab from airport", activities: ["Fort Kochi walk", "Chinese fishing nets", "Kathakali show"] },
      { day: 2, city: "Munnar", title: "Drive to Munnar", description: "Scenic 4-hour drive to Munnar through winding roads. Tea Museum visit and sunset at Top Station.", images: [], meals: ["breakfast", "dinner"], transfers: "Private cab, 4 hrs", activities: ["Tea Museum", "Echo Point", "Top Station sunset"] },
      { day: 3, city: "Munnar", title: "Munnar Sightseeing", description: "Visit Mattupetty Dam, Kundala Lake, and Eravikulam National Park. Afternoon free for nature walks.", images: [], meals: ["breakfast"], transfers: "Local cab", activities: ["Eravikulam NP", "Mattupetty Dam", "Tea plantation walk"] },
      { day: 4, city: "Thekkady", title: "Thekkady Wildlife", description: "Drive to Thekkady (3 hrs). Periyar Wildlife Sanctuary boat ride. Afternoon spice plantation tour.", images: [], meals: ["breakfast", "dinner"], transfers: "Private cab, 3 hrs", activities: ["Periyar boat ride", "Spice plantation", "Ayurvedic consultation"] },
      { day: 5, city: "Alleppey", title: "Houseboat Cruise", description: "Check into a premium houseboat. Cruise through the backwaters of Alleppey, passing villages and coconut groves.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Private car to jetty, 3 hrs", activities: ["Backwater cruise", "Village walk", "Fishing with locals"] },
      { day: 6, city: "Kovalam → Cochin", title: "Beach Morning & Departure", description: "Early checkout, drive to Kovalam for sunrise on the crescent beach. Transfer to Cochin airport.", images: [], meals: ["breakfast"], transfers: "Private cab to airport", activities: ["Kovalam beach", "Lighthouse visit"] },
    ],
    variants: [
      { key: "3-star", label: "Comfort", hotelCategory: 3, durationDays: 6, durationNights: 5, pricePerAdultINR: 18999, pricePerChildINR: 14000, singleSupplementINR: 10000, originalPricePerAdultINR: 23999, inclusionsExtra: ["3-star hotels", "Standard houseboat"], isDefault: false },
      { key: "4-star", label: "Premium", hotelCategory: 4, durationDays: 6, durationNights: 5, pricePerAdultINR: 28999, pricePerChildINR: 19000, singleSupplementINR: 16000, originalPricePerAdultINR: 34999, inclusionsExtra: ["4-star resorts", "Premium houseboat", "Ayurvedic massage", "Kathakali dinner show"], isDefault: true },
      { key: "5-star", label: "Luxury", hotelCategory: 5, durationDays: 6, durationNights: 5, pricePerAdultINR: 54999, pricePerChildINR: 35000, singleSupplementINR: 30000, originalPricePerAdultINR: 66999, inclusionsExtra: ["5-star resorts", "Luxury houseboat", "Full Ayurveda package"], isDefault: false },
    ],
    departures: makeDepartures(5, 6, 14),
    departureCities: ["Delhi", "Mumbai", "Bangalore", "Chennai"],
    startingPriceINR: 18999,
    originalPriceINR: 23999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: false,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["September", "October", "November", "December", "January", "February"],
    inclusions: ["5 nights accommodation on twin sharing", "Daily breakfast; dinner on selected days", "All transfers by private AC car", "Overnight premium houseboat with all meals", "Periyar Wildlife Sanctuary boat ride", "Kathakali and Kalaripayattu show", "One Ayurvedic full-body massage"],
    exclusions: ["Flights/train to Cochin", "Lunch (except houseboat)", "Personal expenses and tips", "Camera fees at monuments", "Optional activities"],
    importantInfo: ["Carry light cotton clothes and a light jacket", "Sunscreen and hat essential for Munnar", "Carry a valid ID for all internal transfers"],
    visaDetails: "",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 5 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing basis", "Houseboat cruise may be shared with other groups"],
    hotels: [
      { city: "Cochin", name: "Old Harbour Hotel", category: 4, nights: 1, note: "Heritage hotel in Fort Kochi" },
      { city: "Munnar", name: "Foggy Knolls Resort", category: 4, nights: 2, note: "Valley view rooms" },
      { city: "Thekkady", name: "Thekkady Wild Ridge", category: 4, nights: 1, note: "Near Periyar sanctuary" },
      { city: "Alleppey", name: "Premium Houseboat", category: 4, nights: 1, note: "1 bedroom AC houseboat" },
    ],
    faqs: [
      { question: "Is Kerala safe for solo female travellers?", answer: "Kerala is one of the safest and most tourist-friendly states in India." },
      { question: "Is the houseboat safe?", answer: "All houseboats are licensed and equipped with life jackets and first aid." },
    ],
    ratingAverage: 4.8,
    ratingCount: 289,
    isFeatured: true,
    isTrending: false,
    isBestseller: true,
    status: "published",
    seo: { title: "Kerala God's Own Country — 6 Days 5 Nights from 18999", description: "Kerala backwater, hill station, and Ayurveda package with houseboat stay." },
    viewCount: 7800,
    enquiryCount: 210,
    bookingCount: 140,
    deletedAt: null,
  },

  // 5. Leh Ladakh Expedition
  {
    title: "Leh Ladakh Expedition",
    slug: "leh-ladakh-expedition",
    subtitle: "Pangong, Nubra, Khardung La — the ultimate Himalayan road trip",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Leh", "Nubra Valley", "Pangong Tso", "Khardung La", "Diskit"],
    scope: "domestic",
    tripTypes: ["adventure", "road-trip"],
    collections: ["adventure-tours", "trending-international"],
    durationDays: 8,
    durationNights: 7,
    heroImage: img("https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=1200&q=80", "Pangong Lake"),
    gallery: [
      img("https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80", "Ladakh mountains"),
      img("https://images.unsplash.com/photo-1604391652849-3e77942344c9?w=800&q=80", "Nubra Valley camel"),
    ],
    overview: "Eight days in the high Himalayas — the ultimate road trip. Fly into Leh, acclimatise, then conquer Khardung La, camp at Pangong Lake, ride camels in Nubra Valley, and visit ancient monasteries.",
    highlights: ["Khardung La — one of the world's highest motorable passes", "2 nights camping at Pangong Lake", "Camel safari in Nubra Valley", "Diskit Monastery and Maitreya Buddha", "Shanti Stupa and Leh Palace", "Inner Line Permit included"],
    itinerary: [
      { day: 1, city: "Leh", title: "Arrival & Acclimatisation", description: "Fly into Leh Kushok Bakula Rimpochee Airport (3,500m). Rest day for acclimatisation.", images: [], meals: ["lunch", "dinner"], transfers: "Airport pickup", activities: ["Shanti Stupa", "Leh Market walk", "Acclimatisation rest"] },
      { day: 2, city: "Leh", title: "Leh Local Sightseeing", description: "Visit Leh Palace, Jama Masjid, and the Hall of Fame museum.", images: [], meals: ["breakfast", "dinner"], transfers: "Local cab", activities: ["Leh Palace", "Hall of Fame", "Jama Masjid"] },
      { day: 3, city: "Nubra Valley", title: "Khardung La & Nubra Valley", description: "Cross Khardung La (5,359m). Descend into Nubra Valley for an evening double-hump camel safari.", images: [], meals: ["breakfast", "dinner"], transfers: "Private 4x4, 4-5 hrs", activities: ["Khardung La", "Nubra camel safari", "Sand dunes"] },
      { day: 4, city: "Pangong Tso", title: "Pangong Lake", description: "Drive from Nubra to Pangong Tso (160 km). The lake changes colour every hour. Overnight camp by the lake.", images: [], meals: ["breakfast", "lunch", "dinner"], transfers: "Private 4x4, 5 hrs", activities: ["Pangong Lake", "Stargazing", "Campfire"] },
      { day: 5, city: "Pangong Tso → Leh", title: "Pangong Sunrise & Return", description: "Sunrise over Pangong. Return to Leh via Chang La pass.", images: [], meals: ["breakfast", "lunch"], transfers: "Private 4x4, 5-6 hrs", activities: ["Pangong sunrise", "Chang La pass", "Thiksey Monastery"] },
      { day: 6, city: "Leh → Sham Valley", title: "Sham Valley Monasteries", description: "Visit Alchi Gompa, Basgo, and Likir Monasteries.", images: [], meals: ["breakfast", "dinner"], transfers: "Private 4x4", activities: ["Alchi Gompa", "Likir Monastery", "Magnetic Hill"] },
      { day: 7, city: "Leh", title: "Free Day in Leh", description: "Rest and acclimatisation day. Optional rafting on the Zanskar River or a day trip to Tso Moriri.", images: [], meals: ["breakfast"], transfers: "", activities: ["Leh exploration", "Rafting (optional)"], optionalExperiences: ["Zanskar rafting", "Tso Moriri day trip"] },
      { day: 8, city: "Leh → Departure", title: "Farewell to the Roof of the World", description: "Morning at leisure. Transfer to Leh airport.", images: [], meals: ["breakfast"], transfers: "Airport transfer", activities: ["Last-minute souvenir shopping"] },
    ],
    variants: [
      { key: "backpacker", label: "Backpacker", hotelCategory: 3, durationDays: 8, durationNights: 7, pricePerAdultINR: 24999, pricePerChildINR: 20000, singleSupplementINR: 8000, originalPricePerAdultINR: 29999, inclusionsExtra: ["Guesthouse", "Shared 4x4"], isDefault: false },
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 8, durationNights: 7, pricePerAdultINR: 32999, pricePerChildINR: 25000, singleSupplementINR: 14000, originalPricePerAdultINR: 39999, inclusionsExtra: ["3-star hotel", "Private 4x4", "Pangong camp", "All permits"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 8, durationNights: 7, pricePerAdultINR: 49999, pricePerChildINR: 35000, singleSupplementINR: 25000, originalPricePerAdultINR: 59999, inclusionsExtra: ["4-star hotel", "Luxury camp at Pangong", "Private driver", "All meals"], isDefault: false },
    ],
    departures: makeDepartures(21, 4, 21),
    departureCities: ["Delhi", "Mumbai"],
    startingPriceINR: 24999,
    originalPriceINR: 29999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "group",
    instantConfirmation: false,
    recommendedSeason: ["May", "June", "July", "August", "September"],
    inclusions: ["Return flights from Delhi/Mumbai", "7 nights accommodation", "All transfers by private 4x4", "Inner Line Permit for all restricted areas", "Pangong Lake camping arrangement", "Camel safari in Nubra Valley", "Monastery visits and entry fees", "Oxygen cylinders for emergencies", "Travel insurance"],
    exclusions: ["Personal expenses and tips", "Lunch during transit days", "Emergency evacuation costs", "Rent for warm clothing", "Optional rafting"],
    importantInfo: ["Carry multiple layers of warm clothing", "Stay hydrated and avoid alcohol for the first 48 hours", "Carry sunscreen SPF 50+ — UV is intense at altitude"],
    visaDetails: "",
    cancellationPolicy: [
      { window: "More than 30 days before departure", charge: "25% of total" },
      { window: "15–30 days before departure", charge: "50% of total" },
      { window: "Less than 15 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["50% advance at booking", "Balance 10 days before departure"],
    termsAndConditions: ["Minimum age: 7 years", "Children below 5 years not recommended", "Itinerary may change based on weather and road conditions"],
    hotels: [
      { city: "Leh", name: "The Grand Dragon Ladakh", category: 4, nights: 5, note: "Best hotel in Leh, panoramic mountain views" },
      { city: "Nubra Valley", name: "Nubra Ethnic Camp", category: 3, nights: 1, note: "Luxury Swiss tents with attached bath" },
      { city: "Pangong", name: "Pangong Retreat Camp", category: 3, nights: 1, note: "Lakeside luxury camping" },
    ],
    faqs: [
      { question: "Is Leh Ladakh safe?", answer: "Yes, Ladakh is one of the safest regions in India. The army presence ensures security." },
      { question: "Do I need to carry oxygen?", answer: "We provide oxygen cylinders. Carry Diamox (acetazolamide) after consulting your doctor." },
    ],
    ratingAverage: 4.6,
    ratingCount: 198,
    isFeatured: true,
    isTrending: true,
    isBestseller: false,
    status: "published",
    seo: { title: "Leh Ladakh Expedition — 8 Days from 24999 with Flights", description: "Complete Ladakh package with Khardung La, Pangong Lake, Nubra Valley camel safari." },
    viewCount: 6700,
    enquiryCount: 220,
    bookingCount: 110,
    deletedAt: null,
  },

  // 6. Sri Lanka Serenity
  {
    title: "Sri Lanka Serenity",
    slug: "sri-lanka-serenity",
    subtitle: "Ella train, Sigiriya rock, and the southern beaches",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Colombo", "Kandy", "Ella", "Sigiriya", "Mirissa"],
    scope: "international",
    tripTypes: ["honeymoon", "leisure", "wildlife"],
    collections: ["trending-international", "honeymoon-escapes", "affordable-getaways"],
    durationDays: 6,
    durationNights: 5,
    heroImage: img("https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?w=1200&q=80", "Sigiriya Rock Fortress"),
    gallery: [
      img("https://images.unsplash.com/photo-1544207240-8c9b3a3e3f5c?w=800&q=80", "Ella train"),
      img("https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80", "Sri Lankan tea plantation"),
    ],
    overview: "Six days exploring Sri Lanka's cultural triangle and south coast. Climb the ancient Sigiriya Rock, ride the world's most scenic train to Ella, go on a safari in Yala, and swim in the Indian Ocean at Mirissa.",
    highlights: ["Scenic train ride from Kandy to Ella", "Sigiriya Rock Fortress climb", "Yala National Park safari", "Temple of the Sacred Tooth Relic", "Whale watching at Mirissa", "Ceylon tea factory tour"],
    itinerary: [
      { day: 1, city: "Colombo", title: "Arrival in Colombo", description: "Arrive at CMB airport. City tour — Gangaramaya Temple, Independence Square, Galle Face Green sunset.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Colombo city tour", "Galle Face Green"] },
      { day: 2, city: "Kandy", title: "Kandy — Sacred City", description: "Drive to Kandy (3 hrs). Visit the Temple of the Tooth Relic, Royal Botanic Gardens, and a cultural dance show.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car, 3 hrs", activities: ["Temple of the Tooth", "Botanic Gardens", "Cultural dance show"] },
      { day: 3, city: "Ella", title: "Scenic Train to Ella", description: "Take the world-famous train from Kandy to Ella. Afternoon visit to Nine Arch Bridge and Little Adam's Peak.", images: [], meals: ["breakfast"], transfers: "Train from Kandy to Ella", activities: ["Scenic train ride", "Nine Arch Bridge", "Little Adam's Peak trek"] },
      { day: 4, city: "Sigiriya", title: "Sigiriya Rock Fortress", description: "Climb the ancient rock fortress. Explore the Dambulla cave temples on the way back.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car", activities: ["Sigiriya climb", "Dambulla caves", "Village tour"] },
      { day: 5, city: "Yala → Mirissa", title: "Yala Safari & Southern Beaches", description: "Morning safari at Yala National Park. Drive to Mirissa for sunset.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car, 3.5 hrs", activities: ["Yala safari", "Whale watching (seasonal)", "Mirissa beach"] },
      { day: 6, city: "Mirissa → Colombo", title: "Farewell Sri Lanka", description: "Morning at leisure. Drive to Colombo airport.", images: [], meals: ["breakfast"], transfers: "Private car to airport", activities: ["Beach morning", "Last-minute shopping"] },
    ],
    variants: [
      { key: "budget", label: "Budget", hotelCategory: 3, durationDays: 6, durationNights: 5, pricePerAdultINR: 27999, pricePerChildINR: 21000, singleSupplementINR: 12000, originalPricePerAdultINR: 34999, inclusionsExtra: ["Budget guesthouses", "Public transport on train"], isDefault: false },
      { key: "comfort", label: "Comfort", hotelCategory: 4, durationDays: 6, durationNights: 5, pricePerAdultINR: 39999, pricePerChildINR: 28000, singleSupplementINR: 18000, originalPricePerAdultINR: 49999, inclusionsExtra: ["4-star hotels", "Private transfers", "Yala safari with tracker"], isDefault: true },
      { key: "luxury", label: "Luxury", hotelCategory: 5, durationDays: 6, durationNights: 5, pricePerAdultINR: 67999, pricePerChildINR: 45000, singleSupplementINR: 35000, originalPricePerAdultINR: 81999, inclusionsExtra: ["5-star resorts", "Private guide", "Whale watching cruise"], isDefault: false },
    ],
    departures: makeDepartures(5, 6, 14),
    departureCities: ["Delhi", "Mumbai", "Chennai"],
    startingPriceINR: 27999,
    originalPriceINR: 34999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: true,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: true,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["December", "January", "February", "March"],
    inclusions: ["Return flights from major Indian cities", "5 nights accommodation on twin sharing", "Private AC vehicle for all transfers", "Yala National Park safari with tracker", "Scenic train tickets (Kandy to Ella)", "Sri Lanka ETA processing", "All monument entry fees"],
    exclusions: ["Lunch and personal meals", "Tips and personal expenses", "Optional activities not listed", "Travel insurance", "Camera fees"],
    importantInfo: ["Passport must be valid for 6 months", "Carry USD for visa fee and tips", "Train tickets in Sri Lanka sell out fast — book early"],
    visaDetails: "Indian passport holders need an Electronic Travel Authorization (ETA) — we assist with the application.",
    cancellationPolicy: [
      { window: "More than 21 days before departure", charge: "20% of total" },
      { window: "10–21 days before departure", charge: "50% of total" },
      { window: "Less than 10 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["30% advance at booking", "Balance 15 days before departure"],
    termsAndConditions: ["Prices per person on twin sharing", "Itinerary subject to train availability", "Safari sightings not guaranteed"],
    hotels: [
      { city: "Colombo", name: "Cinnamon Grand Colombo", category: 5, nights: 1, note: "City centre, rooftop pool" },
      { city: "Kandy", name: "Earl's Regency", category: 4, nights: 1, note: "Near Temple of the Tooth" },
      { city: "Ella", name: "Ella Jungle Resort", category: 4, nights: 1, note: "Mountain views, near Nine Arch Bridge" },
      { city: "Mirissa", name: "Cape Weligama", category: 5, nights: 1, note: "Luxury cliffside resort" },
    ],
    faqs: [
      { question: "Is Sri Lanka budget-friendly?", answer: "Yes! Sri Lanka offers great value for money — meals, accommodation, and transport are very affordable." },
    ],
    ratingAverage: 4.6,
    ratingCount: 176,
    isFeatured: true,
    isTrending: false,
    isBestseller: false,
    status: "published",
    seo: { title: "Sri Lanka Serenity — 6 Days 5 Nights from 27999", description: "Sri Lanka tour with Sigiriya, Ella train, Yala safari and Mirissa beach." },
    viewCount: 5400,
    enquiryCount: 155,
    bookingCount: 88,
    deletedAt: null,
  },

  // 7. Goa Beach Retreat
  {
    title: "Goa Beach Retreat",
    slug: "goa-beach-retreat",
    subtitle: "Sun-kissed beaches, Portuguese heritage, and seafood feasts",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["North Goa", "Old Goa", "South Goa", "Dudhsagar"],
    scope: "domestic",
    tripTypes: ["beach", "leisure", "party"],
    collections: ["best-of-india", "affordable-getaways", "weekend-breaks"],
    durationDays: 4,
    durationNights: 3,
    heroImage: img("https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80", "Goa beach palm trees"),
    gallery: [
      img("https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", "Goa Palolem beach"),
      img("https://images.unsplash.com/photo-1593368607364-2bcde5e2ffa6?w=800&q=80", "Goa Portuguese church"),
    ],
    overview: "Four days of pure Goan life — golden beaches, Portuguese churches, spice plantations, and the legendary Dudhsagar Falls. From the buzz of Baga to the calm of Agonda.",
    highlights: ["Dudhsagar Falls day trip", "Old Goa UNESCO heritage churches", "Baga & Anjuna beach time", "Spice plantation tour with Goan lunch", "Sunset river cruise on Mandovi", "Dolphin spotting boat ride"],
    itinerary: [
      { day: 1, city: "North Goa", title: "Arrival & North Goa Beaches", description: "Arrive at Goa Airport. Transfer to North Goa resort. Evening on Baga Beach.", images: [], meals: ["dinner"], transfers: "Airport transfer, 45 min", activities: ["Baga Beach", "Water sports"] },
      { day: 2, city: "Old Goa", title: "Heritage & Spice Plantation", description: "Morning visit to UNESCO churches in Old Goa. Afternoon spice plantation tour with traditional Goan lunch.", images: [], meals: ["breakfast", "lunch"], transfers: "Private cab", activities: ["Old Goa churches", "Spice plantation tour", "Traditional Goan lunch"] },
      { day: 3, city: "South Goa", title: "Dudhsagar Falls & South Goa", description: "Day trip to Dudhsagar Falls via Jeep safari. Afternoon in South Goa — Palolem and Agonda beaches.", images: [], meals: ["breakfast", "dinner"], transfers: "Private cab + Jeep", activities: ["Dudhsagar Falls", "Jeep safari", "Palolem Beach"] },
      { day: 4, city: "Goa", title: "River Cruise & Departure", description: "Morning dolphin boat ride. Transfer to Goa Airport.", images: [], meals: ["breakfast"], transfers: "Airport transfer", activities: ["Dolphin spotting", "Sunset river cruise"] },
    ],
    variants: [
      { key: "budget", label: "Budget", hotelCategory: 3, durationDays: 4, durationNights: 3, pricePerAdultINR: 10999, pricePerChildINR: 7000, singleSupplementINR: 5000, originalPricePerAdultINR: 13999, inclusionsExtra: ["Budget beach resort", "Scooty rental 1 day"], isDefault: false },
      { key: "standard", label: "Standard", hotelCategory: 3, durationDays: 4, durationNights: 3, pricePerAdultINR: 16999, pricePerChildINR: 11000, singleSupplementINR: 8000, originalPricePerAdultINR: 21999, inclusionsExtra: ["3-star beach resort", "Private cab for sightseeing", "Dudhsagar jeep safari"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 4, durationDays: 4, durationNights: 3, pricePerAdultINR: 28999, pricePerChildINR: 18000, singleSupplementINR: 15000, originalPricePerAdultINR: 35999, inclusionsExtra: ["4-star beach resort", "Private car", "Private yacht cruise", "Candlelight dinner"], isDefault: false },
    ],
    departures: makeDepartures(2, 8, 7),
    departureCities: ["Delhi", "Mumbai", "Bangalore", "Pune", "Hyderabad"],
    startingPriceINR: 10999,
    originalPriceINR: 13999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: false,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 3,
    tripStyle: "private",
    instantConfirmation: true,
    recommendedSeason: ["November", "December", "January", "February", "March"],
    inclusions: ["3 nights accommodation on twin sharing", "Daily breakfast", "All transfers by private AC car", "Dudhsagar Falls day trip with Jeep safari", "Old Goa heritage churches tour", "Spice plantation tour with Goan lunch", "Dolphin spotting boat ride", "Water sports at Baga Beach (1 activity)"],
    exclusions: ["Flights/train to Goa", "Lunch and dinner (except spice plantation lunch)", "Personal expenses and tips", "Additional water sports"],
    importantInfo: ["Water sports available October to May only", "Dudhsagar jeep safari may be cancelled during heavy monsoon", "Carry swimwear and sunscreen", "Best time: November to March"],
    visaDetails: "",
    cancellationPolicy: [
      { window: "More than 7 days before departure", charge: "20% of total" },
      { window: "3–7 days before departure", charge: "50% of total" },
      { window: "Less than 3 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["50% advance at booking", "Balance at check-in or 2 days before departure"],
    termsAndConditions: ["Peak season prices (Dec 20 – Jan 5) are 30% higher", "Hotel check-in at 3 PM"],
    hotels: [{ city: "North Goa", name: "Resort De Goa", category: 3, nights: 3, note: "Near Baga Beach, pool, restaurant" }],
    faqs: [
      { question: "Which Goa is best — North or South?", answer: "North Goa for nightlife and water sports; South Goa for peace and quiet beaches. We cover both!" },
    ],
    ratingAverage: 4.2,
    ratingCount: 410,
    isFeatured: true,
    isTrending: false,
    isBestseller: false,
    status: "published",
    seo: { title: "Goa Beach Retreat — 4 Days 3 Nights from 10999", description: "Goa weekend package with Dudhsagar, beaches and heritage churches." },
    viewCount: 12400,
    enquiryCount: 340,
    bookingCount: 210,
    deletedAt: null,
  },

  // 8. Golden Triangle
  {
    title: "Golden Triangle",
    slug: "golden-triangle",
    subtitle: "Delhi — Agra — Jaipur, India's classic royal circuit",
    destination: "" as never,
    additionalDestinations: [],
    citiesCovered: ["Delhi", "Agra", "Jaipur", "Fatehpur Sikri"],
    scope: "domestic",
    tripTypes: ["heritage", "family", "honeymoon"],
    collections: ["best-of-india", "weekend-breaks", "family-holidays"],
    durationDays: 5,
    durationNights: 4,
    heroImage: img("https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&q=80", "Taj Mahal sunrise"),
    gallery: [
      img("https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80", "Amber Fort"),
      img("https://images.unsplash.com/photo-1580137187710-1c31e9e2dd17?w=800&q=80", "Qutub Minar"),
    ],
    overview: "The classic Indian introduction: Delhi's Mughal monuments, the Taj Mahal at sunrise in Agra, and the royal palaces of Jaipur. A perfect first trip to India that covers the three most iconic cities.",
    highlights: ["Taj Mahal sunrise visit", "Red Fort and Jama Masjid in Delhi", "Amber Fort elephant ride in Jaipur", "City Palace and Hawa Mahal", "Fatehpur Sikri ghost city", "Chokhi Dhani ethnic village dinner"],
    itinerary: [
      { day: 1, city: "Delhi", title: "Delhi — Old & New", description: "Full-day sightseeing: Qutub Minar, Humayun's Tomb, India Gate, Rajpath, Gurudwara Bangla Sahib. Evening Chandni Chowk food walk.", images: [], meals: ["dinner"], transfers: "Airport pickup", activities: ["Qutub Minar", "India Gate", "Chandni Chowk food walk"] },
      { day: 2, city: "Delhi → Agra", title: "Agra — Taj Mahal & Red Fort", description: "Drive to Agra (3 hrs). Visit the Taj Mahal at sunset and Agra Fort.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car, 3 hrs", activities: ["Taj Mahal sunset", "Agra Fort", "Mehtab Bagh"] },
      { day: 3, city: "Agra → Fatehpur Sikri → Jaipur", title: "Fatehpur Sikri & Pink City", description: "Sunrise at Taj Mahal. Drive to Fatehpur Sikri, then continue to Jaipur.", images: [], meals: ["breakfast", "dinner"], transfers: "Private car, 5 hrs with stops", activities: ["Taj sunrise", "Fatehpur Sikri", "Jaipur market walk"] },
      { day: 4, city: "Jaipur", title: "Jaipur — Pink City Full Day", description: "Amber Fort with elephant ride, City Palace, Jantar Mantar, Hawa Mahal. Evening at Chokhi Dhani.", images: [], meals: ["breakfast", "dinner"], transfers: "Local sightseeing car", activities: ["Amber Fort elephant ride", "City Palace", "Hawa Mahal", "Chokhi Dhani dinner"] },
      { day: 5, city: "Jaipur → Delhi", title: "Return to Delhi", description: "Drive back to Delhi. En route stop at Neemrana Fort or Sambhar Salt Lake.", images: [], meals: ["breakfast"], transfers: "Private car, 5 hrs", activities: ["En route sightseeing"] },
    ],
    variants: [
      { key: "budget", label: "Budget", hotelCategory: 3, durationDays: 5, durationNights: 4, pricePerAdultINR: 11999, pricePerChildINR: 8000, singleSupplementINR: 6000, originalPricePerAdultINR: 15999, inclusionsExtra: ["3-star hotels", "AC sedan transfers"], isDefault: false },
      { key: "standard", label: "Standard", hotelCategory: 4, durationDays: 5, durationNights: 4, pricePerAdultINR: 19999, pricePerChildINR: 14000, singleSupplementINR: 10000, originalPricePerAdultINR: 25999, inclusionsExtra: ["4-star hotels", "Private AC car", "Elephant ride", "Chokhi Dhani dinner"], isDefault: true },
      { key: "premium", label: "Premium", hotelCategory: 5, durationDays: 5, durationNights: 4, pricePerAdultINR: 38999, pricePerChildINR: 25000, singleSupplementINR: 20000, originalPricePerAdultINR: 47999, inclusionsExtra: ["5-star hotels", "Private luxury car", "Taj Mahal guide", "Royal dinner"], isDefault: false },
    ],
    departures: makeDepartures(3, 8, 7),
    departureCities: ["Delhi"],
    startingPriceINR: 11999,
    originalPriceINR: 15999,
    priceBasis: "per_person",
    taxPercent: 5,
    flightsIncluded: false,
    mealsIncluded: true,
    activitiesIncluded: true,
    visaIncluded: false,
    transfersIncluded: true,
    hotelCategory: 4,
    tripStyle: "group",
    instantConfirmation: true,
    recommendedSeason: ["October", "November", "December", "January", "February", "March"],
    inclusions: ["4 nights accommodation on twin sharing", "Daily breakfast and dinner", "All transfers by private AC car", "Taj Mahal entry and guide", "Amber Fort elephant ride", "Chokhi Dhani ethnic village dinner", "Monument entry fees", "Travel insurance"],
    exclusions: ["Flights / train to Delhi", "Lunch on all days", "Camera fees at monuments", "Personal expenses", "Tips to drivers and guides"],
    importantInfo: ["Taj Mahal is closed on Fridays", "Carry comfortable walking shoes", "Dress modestly for religious sites", "Best time: October to March"],
    visaDetails: "",
    cancellationPolicy: [
      { window: "More than 15 days before departure", charge: "20% of total" },
      { window: "7–15 days before departure", charge: "50% of total" },
      { window: "Less than 7 days before departure", charge: "100% of total" },
    ],
    paymentPolicy: ["50% advance at booking", "Balance 5 days before departure"],
    termsAndConditions: ["Group size: 6 to 20", "Minimum 4 pax required for departure", "Subject to availability of monument tickets"],
    hotels: [
      { city: "Delhi", name: "The Park Plaza", category: 4, nights: 1, note: "Connaught Place, central Delhi" },
      { city: "Agra", name: "Radisson Blu Agra", category: 5, nights: 1, note: "Taj view rooms available" },
      { city: "Jaipur", name: "Trident Jaipur", category: 5, nights: 2, note: "Near Amer Road, beautiful lake views" },
    ],
    faqs: [
      { question: "Is the Golden Triangle safe?", answer: "Yes, it's the most tourist-friendly circuit in India with excellent infrastructure." },
      { question: "How far in advance should I book?", answer: "At least 2-3 weeks ahead — Taj Mahal slots sell out fast." },
    ],
    ratingAverage: 4.4,
    ratingCount: 520,
    isFeatured: true,
    isTrending: false,
    isBestseller: true,
    status: "published",
    seo: { title: "Golden Triangle Tour — 5 Days 4 Nights from 11999", description: "Delhi Agra Jaipur tour with Taj Mahal sunrise, Amber Fort, and heritage hotels." },
    viewCount: 15800,
    enquiryCount: 450,
    bookingCount: 280,
    deletedAt: null,
  },
];

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

async function main() {
  await connectDB();

  // Upsert destinations
  for (const dest of destinations) {
    const existing = await Destination.findOne({ slug: dest.slug });
    if (existing) {
      await Destination.updateOne({ _id: existing._id }, { $set: dest });
      console.log(`  Updated destination: ${dest.name}`);
    } else {
      await Destination.create(dest as never);
      console.log(`  Created destination: ${dest.name}`);
    }
  }

  // Create collections if missing
  const collections: Omit<ICategory, "_id" | "createdAt" | "updatedAt">[] = [
    { name: "Trending International", slug: "trending-international", kind: "trip_type", order: 1 },
    { name: "Best of India", slug: "best-of-india", kind: "trip_type", order: 2 },
    { name: "Honeymoon Escapes", slug: "honeymoon-escapes", kind: "trip_type", order: 3 },
    { name: "Family Holidays", slug: "family-holidays", kind: "trip_type", order: 4 },
    { name: "Affordable Getaways", slug: "affordable-getaways", kind: "trip_type", order: 5 },
    { name: "Adventure Tours", slug: "adventure-tours", kind: "trip_type", order: 6 },
    { name: "Weekend Breaks", slug: "weekend-breaks", kind: "trip_type", order: 7 },
    { name: "Group Departures", slug: "group-departures", kind: "trip_type", order: 8 },
    { name: "Flight Inclusive", slug: "flight-inclusive", kind: "trip_type", order: 9 },
  ];

  for (const cat of collections) {
    const existing = await Category.findOne({ slug: cat.slug });
    if (!existing) {
      await Category.create(cat as never);
      console.log(`  Created collection: ${cat.name}`);
    }
  }

  // Upsert packages
  for (const pkg of packages) {
    const destSlug = (destinations.find((d) => d.name === pkg.citiesCovered[0])?.slug) || "";
    const destRecord = await Destination.findOne({ slug: destSlug });
    const resolvedDest = destRecord?._id || (await Destination.findOne({ name: pkg.citiesCovered[0] }))?._id;

    const existing = await Package.findOne({ slug: pkg.slug });
    const { destination: _omitDest, ...pkgWithoutDest } = pkg;
    const doc: Omit<Parameters<typeof Package.create>[0], "destination"> & { destination: string } = {
      ...pkgWithoutDest,
      destination: resolvedDest!.toString(),
    };

    if (existing) {
      await Package.updateOne({ _id: existing._id }, { $set: doc });
      console.log(`  Updated package: ${pkg.title}`);
    } else {
      await Package.create(doc);
      console.log(`  Created package: ${pkg.title}`);
    }
  }

  console.log(`\nDone — ${packages.length} demo packages processed.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed packages failed:", err);
  process.exit(1);
});
